namespace SAMMI.PP
{
    partial class PP3700
    {
        /// <summary>
        /// 필수 디자이너 변수입니다.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 사용 중인 모든 리소스를 정리합니다.
        /// </summary>
        /// <param name="disposing">관리되는 리소스를 삭제해야 하면 true이고, 그렇지 않으면 false입니다.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form 디자이너에서 생성한 코드

        /// <summary>
        /// 디자이너 지원에 필요한 메서드입니다.
        /// 이 메서드의 내용을 코드 편집기로 수정하지 마십시오.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance122 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinSchedule.CalendarCombo.DateButton dateButton1 = new Infragistics.Win.UltraWinSchedule.CalendarCombo.DateButton();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinSchedule.CalendarCombo.DateButton dateButton2 = new Infragistics.Win.UltraWinSchedule.CalendarCombo.DateButton();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance124 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance123 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance137 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance125 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance126 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance127 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance128 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance129 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance130 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance131 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance132 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance133 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance134 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance135 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance136 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance65 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance66 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance67 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance68 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance69 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance70 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance71 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance72 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance73 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance74 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance75 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance76 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance77 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance78 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance79 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PP3700));
            Infragistics.Win.Appearance appearance80 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand1 = new Infragistics.Win.UltraWinGrid.UltraGridBand("dTable1", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn5 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("WorkCenterCode");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn6 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("WorkCenterName");
            Infragistics.Win.Appearance appearance81 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance82 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance83 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance84 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance85 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance86 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance87 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance88 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance89 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance90 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance91 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance92 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance93 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance94 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand2 = new Infragistics.Win.UltraWinGrid.UltraGridBand("dTable1", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn1 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("LineCode");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn2 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("LineName");
            Infragistics.Win.Appearance appearance95 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance96 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance97 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance98 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance99 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance100 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance101 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance102 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance103 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance104 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance105 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance106 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance107 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance108 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand3 = new Infragistics.Win.UltraWinGrid.UltraGridBand("dTable1", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn13 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("OPCode");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn14 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("OPName");
            Infragistics.Win.Appearance appearance109 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance110 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance111 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance112 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance113 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance114 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance115 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance116 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance117 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance118 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance119 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance120 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance121 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            this.grid1 = new SAMMI.Control.Grid(this.components);
            this.txtLineName = new System.Windows.Forms.TextBox();
            this.txtOPCode = new System.Windows.Forms.TextBox();
            this.txtOPName = new System.Windows.Forms.TextBox();
            this.sLabel6 = new SAMMI.Control.SLabel();
            this.CboStartdate_H = new Infragistics.Win.UltraWinSchedule.UltraCalendarCombo();
            this.CboEnddate_H = new Infragistics.Win.UltraWinSchedule.UltraCalendarCombo();
            this.ultraLabel4 = new Infragistics.Win.Misc.UltraLabel();
            this.sLabel5 = new SAMMI.Control.SLabel();
            this.lblLineCode = new SAMMI.Control.SLabel();
            this.lblOPCode = new SAMMI.Control.SLabel();
            this.sLabel1 = new SAMMI.Control.SLabel();
            this.lblUseFlag = new SAMMI.Control.SLabel();
            this.cboGubun = new SAMMI.Control.SCodeNMComboBox();
            this.cboDaynight_H = new SAMMI.Control.SCodeNMComboBox();
            this.CboShiftGB = new SAMMI.Control.SCodeNMComboBox();
            this.CboDayNight = new SAMMI.Control.SCodeNMComboBox();
            this.CboWorkcentercode = new SAMMI.Control.ScboGetWorkCenterCode();
            this.CboLineCode = new SAMMI.Control.ScboGetLineCode();
            this.CboOpcode = new SAMMI.Control.ScboGetOPCode();
            this.sLabel2 = new SAMMI.Control.SLabel();
            this.cboPlantCode_H = new SAMMI.Control.SCodeNMComboBox();
            ((System.ComponentModel.ISupportInitialize)(this.gbxHeader)).BeginInit();
            this.gbxHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gbxBody)).BeginInit();
            this.gbxBody.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grid1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboStartdate_H)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboEnddate_H)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboGubun)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboDaynight_H)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboShiftGB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboDayNight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboWorkcentercode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboLineCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboOpcode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboPlantCode_H)).BeginInit();
            this.SuspendLayout();
            // 
            // gbxHeader
            // 
            this.gbxHeader.ContentPadding.Bottom = 2;
            this.gbxHeader.ContentPadding.Left = 2;
            this.gbxHeader.ContentPadding.Right = 2;
            this.gbxHeader.ContentPadding.Top = 4;
            this.gbxHeader.Controls.Add(this.cboPlantCode_H);
            this.gbxHeader.Controls.Add(this.sLabel2);
            this.gbxHeader.Controls.Add(this.cboGubun);
            this.gbxHeader.Controls.Add(this.cboDaynight_H);
            this.gbxHeader.Controls.Add(this.CboStartdate_H);
            this.gbxHeader.Controls.Add(this.CboEnddate_H);
            this.gbxHeader.Controls.Add(this.ultraLabel4);
            this.gbxHeader.Controls.Add(this.sLabel5);
            this.gbxHeader.Controls.Add(this.sLabel1);
            this.gbxHeader.Controls.Add(this.lblUseFlag);
            this.gbxHeader.Size = new System.Drawing.Size(1263, 48);
            // 
            // gbxBody
            // 
            this.gbxBody.ContentPadding.Bottom = 4;
            this.gbxBody.ContentPadding.Left = 4;
            this.gbxBody.ContentPadding.Right = 4;
            this.gbxBody.ContentPadding.Top = 6;
            this.gbxBody.Controls.Add(this.grid1);
            this.gbxBody.Controls.Add(this.txtLineName);
            this.gbxBody.Controls.Add(this.CboShiftGB);
            this.gbxBody.Controls.Add(this.CboDayNight);
            this.gbxBody.Controls.Add(this.CboWorkcentercode);
            this.gbxBody.Controls.Add(this.txtOPCode);
            this.gbxBody.Controls.Add(this.CboLineCode);
            this.gbxBody.Controls.Add(this.txtOPName);
            this.gbxBody.Controls.Add(this.CboOpcode);
            this.gbxBody.Controls.Add(this.sLabel6);
            this.gbxBody.Controls.Add(this.lblOPCode);
            this.gbxBody.Controls.Add(this.lblLineCode);
            this.gbxBody.Location = new System.Drawing.Point(0, 48);
            this.gbxBody.Size = new System.Drawing.Size(1263, 549);
            // 
            // grid1
            // 
            this.grid1.ContextMenuCopyEnabled = true;
            this.grid1.ContextMenuDeleteEnabled = true;
            this.grid1.ContextMenuExcelEnabled = true;
            this.grid1.ContextMenuInsertEnabled = true;
            this.grid1.ContextMenuPasteEnabled = true;
            appearance40.BackColor = System.Drawing.SystemColors.Window;
            appearance40.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.grid1.DisplayLayout.Appearance = appearance40;
            this.grid1.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grid1.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.grid1.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.Empty;
            appearance41.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance41.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance41.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance41.BorderColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.GroupByBox.Appearance = appearance41;
            appearance42.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grid1.DisplayLayout.GroupByBox.BandLabelAppearance = appearance42;
            this.grid1.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grid1.DisplayLayout.GroupByBox.Hidden = true;
            appearance43.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance43.BackColor2 = System.Drawing.SystemColors.Control;
            appearance43.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance43.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grid1.DisplayLayout.GroupByBox.PromptAppearance = appearance43;
            this.grid1.DisplayLayout.MaxColScrollRegions = 1;
            this.grid1.DisplayLayout.MaxRowScrollRegions = 1;
            appearance44.BackColor = System.Drawing.SystemColors.Window;
            appearance44.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grid1.DisplayLayout.Override.ActiveCellAppearance = appearance44;
            appearance45.BackColor = System.Drawing.SystemColors.Highlight;
            appearance45.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.grid1.DisplayLayout.Override.ActiveRowAppearance = appearance45;
            this.grid1.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.True;
            this.grid1.DisplayLayout.Override.AllowMultiCellOperations = ((Infragistics.Win.UltraWinGrid.AllowMultiCellOperation)((((((((Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.CopyWithHeaders) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Cut) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Delete) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Paste) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Undo) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Redo) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Reserved)));
            this.grid1.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.grid1.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance46.BackColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.Override.CardAreaAppearance = appearance46;
            appearance47.BorderColor = System.Drawing.Color.Silver;
            appearance47.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.grid1.DisplayLayout.Override.CellAppearance = appearance47;
            this.grid1.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.grid1.DisplayLayout.Override.CellPadding = 0;
            appearance48.BackColor = System.Drawing.SystemColors.Control;
            appearance48.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance48.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance48.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance48.BorderColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.Override.GroupByRowAppearance = appearance48;
            appearance49.TextHAlignAsString = "Left";
            this.grid1.DisplayLayout.Override.HeaderAppearance = appearance49;
            this.grid1.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grid1.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance50.BackColor = System.Drawing.SystemColors.Window;
            appearance50.BorderColor = System.Drawing.Color.Silver;
            this.grid1.DisplayLayout.Override.RowAppearance = appearance50;
            this.grid1.DisplayLayout.Override.RowSelectorHeaderStyle = Infragistics.Win.UltraWinGrid.RowSelectorHeaderStyle.SeparateElement;
            this.grid1.DisplayLayout.Override.RowSelectorNumberStyle = Infragistics.Win.UltraWinGrid.RowSelectorNumberStyle.RowIndex;
            appearance51.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grid1.DisplayLayout.Override.TemplateAddRowAppearance = appearance51;
            this.grid1.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grid1.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grid1.DisplayLayout.SelectionOverlayBorderThickness = 2;
            this.grid1.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.grid1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grid1.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.grid1.Location = new System.Drawing.Point(6, 6);
            this.grid1.Name = "grid1";
            this.grid1.Size = new System.Drawing.Size(1251, 537);
            this.grid1.TabIndex = 0;
            this.grid1.Text = "grid1";
            this.grid1.TextRenderingMode = Infragistics.Win.TextRenderingMode.GDI;
            this.grid1.UpdateMode = Infragistics.Win.UltraWinGrid.UpdateMode.OnCellChange;
            this.grid1.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.grid1.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            // 
            // txtLineName
            // 
            this.txtLineName.BackColor = System.Drawing.SystemColors.InactiveBorder;
            this.txtLineName.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtLineName.Location = new System.Drawing.Point(598, 204);
            this.txtLineName.MaxLength = 30;
            this.txtLineName.Name = "txtLineName";
            this.txtLineName.Size = new System.Drawing.Size(199, 25);
            this.txtLineName.TabIndex = 231;
            this.txtLineName.Visible = false;
            // 
            // txtOPCode
            // 
            this.txtOPCode.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtOPCode.Location = new System.Drawing.Point(450, 36);
            this.txtOPCode.Name = "txtOPCode";
            this.txtOPCode.Size = new System.Drawing.Size(119, 25);
            this.txtOPCode.TabIndex = 226;
            this.txtOPCode.Visible = false;
            // 
            // txtOPName
            // 
            this.txtOPName.BackColor = System.Drawing.SystemColors.InactiveBorder;
            this.txtOPName.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtOPName.Location = new System.Drawing.Point(575, 36);
            this.txtOPName.MaxLength = 30;
            this.txtOPName.Name = "txtOPName";
            this.txtOPName.Size = new System.Drawing.Size(199, 25);
            this.txtOPName.TabIndex = 227;
            this.txtOPName.Visible = false;
            // 
            // sLabel6
            // 
            appearance122.FontData.Name = "맑은 고딕";
            appearance122.FontData.SizeInPoints = 9F;
            appearance122.TextHAlignAsString = "Right";
            appearance122.TextVAlignAsString = "Middle";
            this.sLabel6.Appearance = appearance122;
            this.sLabel6.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.sLabel6.DbField = null;
            this.sLabel6.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.sLabel6.Location = new System.Drawing.Point(863, 64);
            this.sLabel6.Name = "sLabel6";
            this.sLabel6.Size = new System.Drawing.Size(130, 27);
            this.sLabel6.TabIndex = 221;
            this.sLabel6.Text = "사업장";
            this.sLabel6.Visible = false;
            // 
            // CboStartdate_H
            // 
            appearance32.FontData.Name = "맑은 고딕";
            appearance32.FontData.SizeInPoints = 9F;
            this.CboStartdate_H.Appearance = appearance32;
            this.CboStartdate_H.DateButtons.Add(dateButton1);
            this.CboStartdate_H.Location = new System.Drawing.Point(270, 14);
            this.CboStartdate_H.Name = "CboStartdate_H";
            this.CboStartdate_H.NonAutoSizeHeight = 26;
            this.CboStartdate_H.Size = new System.Drawing.Size(120, 22);
            this.CboStartdate_H.TabIndex = 2;
            // 
            // CboEnddate_H
            // 
            appearance33.FontData.Name = "맑은 고딕";
            appearance33.FontData.SizeInPoints = 9F;
            this.CboEnddate_H.Appearance = appearance33;
            this.CboEnddate_H.DateButtons.Add(dateButton2);
            this.CboEnddate_H.Location = new System.Drawing.Point(414, 14);
            this.CboEnddate_H.Name = "CboEnddate_H";
            this.CboEnddate_H.NonAutoSizeHeight = 26;
            this.CboEnddate_H.Size = new System.Drawing.Size(120, 22);
            this.CboEnddate_H.TabIndex = 3;
            // 
            // ultraLabel4
            // 
            appearance34.TextHAlignAsString = "Center";
            appearance34.TextVAlignAsString = "Middle";
            this.ultraLabel4.Appearance = appearance34;
            this.ultraLabel4.AutoSize = true;
            this.ultraLabel4.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ultraLabel4.Location = new System.Drawing.Point(396, 16);
            this.ultraLabel4.Name = "ultraLabel4";
            this.ultraLabel4.Size = new System.Drawing.Size(13, 18);
            this.ultraLabel4.TabIndex = 216;
            this.ultraLabel4.Text = "~";
            // 
            // sLabel5
            // 
            appearance39.FontData.Name = "맑은 고딕";
            appearance39.FontData.SizeInPoints = 9F;
            appearance39.TextHAlignAsString = "Right";
            appearance39.TextVAlignAsString = "Middle";
            this.sLabel5.Appearance = appearance39;
            this.sLabel5.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.sLabel5.DbField = null;
            this.sLabel5.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.sLabel5.Location = new System.Drawing.Point(539, 12);
            this.sLabel5.Name = "sLabel5";
            this.sLabel5.Size = new System.Drawing.Size(53, 25);
            this.sLabel5.TabIndex = 215;
            this.sLabel5.Text = "원재료";
            // 
            // lblLineCode
            // 
            appearance124.FontData.Name = "맑은 고딕";
            appearance124.FontData.SizeInPoints = 9F;
            appearance124.TextHAlignAsString = "Right";
            appearance124.TextVAlignAsString = "Middle";
            this.lblLineCode.Appearance = appearance124;
            this.lblLineCode.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblLineCode.DbField = null;
            this.lblLineCode.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblLineCode.Location = new System.Drawing.Point(336, 202);
            this.lblLineCode.Name = "lblLineCode";
            this.lblLineCode.Size = new System.Drawing.Size(130, 27);
            this.lblLineCode.TabIndex = 214;
            this.lblLineCode.Text = "라인";
            this.lblLineCode.Visible = false;
            // 
            // lblOPCode
            // 
            appearance123.FontData.Name = "맑은 고딕";
            appearance123.FontData.SizeInPoints = 9F;
            appearance123.TextHAlignAsString = "Right";
            appearance123.TextVAlignAsString = "Middle";
            this.lblOPCode.Appearance = appearance123;
            this.lblOPCode.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblOPCode.DbField = null;
            this.lblOPCode.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblOPCode.Location = new System.Drawing.Point(314, 34);
            this.lblOPCode.Name = "lblOPCode";
            this.lblOPCode.Size = new System.Drawing.Size(130, 27);
            this.lblOPCode.TabIndex = 213;
            this.lblOPCode.Text = "작업장(공정)";
            this.lblOPCode.Visible = false;
            // 
            // sLabel1
            // 
            appearance137.FontData.Name = "맑은 고딕";
            appearance137.FontData.SizeInPoints = 9F;
            appearance137.TextHAlignAsString = "Right";
            appearance137.TextVAlignAsString = "Middle";
            this.sLabel1.Appearance = appearance137;
            this.sLabel1.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.sLabel1.DbField = null;
            this.sLabel1.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.sLabel1.Location = new System.Drawing.Point(999, 26);
            this.sLabel1.Name = "sLabel1";
            this.sLabel1.Size = new System.Drawing.Size(130, 10);
            this.sLabel1.TabIndex = 211;
            this.sLabel1.Text = "주야구분";
            this.sLabel1.Visible = false;
            // 
            // lblUseFlag
            // 
            appearance38.FontData.Name = "맑은 고딕";
            appearance38.TextHAlignAsString = "Right";
            appearance38.TextVAlignAsString = "Middle";
            this.lblUseFlag.Appearance = appearance38;
            this.lblUseFlag.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblUseFlag.DbField = null;
            this.lblUseFlag.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblUseFlag.Location = new System.Drawing.Point(200, 12);
            this.lblUseFlag.Name = "lblUseFlag";
            this.lblUseFlag.Size = new System.Drawing.Size(64, 27);
            this.lblUseFlag.TabIndex = 210;
            this.lblUseFlag.Text = "생산일자";
            // 
            // cboGubun
            // 
            appearance125.FontData.Name = "맑은 고딕";
            appearance125.FontData.SizeInPoints = 9F;
            this.cboGubun.Appearance = appearance125;
            this.cboGubun.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboGubun.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboGubun.DbConfig = null;
            this.cboGubun.DefaultValue = "ALL";
            appearance3.BackColor = System.Drawing.SystemColors.Window;
            appearance3.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboGubun.DisplayLayout.Appearance = appearance3;
            this.cboGubun.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboGubun.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboGubun.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance4.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance4.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance4.BorderColor = System.Drawing.SystemColors.Window;
            this.cboGubun.DisplayLayout.GroupByBox.Appearance = appearance4;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboGubun.DisplayLayout.GroupByBox.BandLabelAppearance = appearance5;
            this.cboGubun.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance126.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance126.BackColor2 = System.Drawing.SystemColors.Control;
            appearance126.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance126.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboGubun.DisplayLayout.GroupByBox.PromptAppearance = appearance126;
            this.cboGubun.DisplayLayout.MaxColScrollRegions = 1;
            this.cboGubun.DisplayLayout.MaxRowScrollRegions = 1;
            appearance127.BackColor = System.Drawing.SystemColors.Window;
            appearance127.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboGubun.DisplayLayout.Override.ActiveCellAppearance = appearance127;
            appearance128.BackColor = System.Drawing.SystemColors.Highlight;
            appearance128.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboGubun.DisplayLayout.Override.ActiveRowAppearance = appearance128;
            appearance129.FontData.BoldAsString = "True";
            this.cboGubun.DisplayLayout.Override.ActiveRowCellAppearance = appearance129;
            this.cboGubun.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboGubun.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboGubun.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance130.BackColor = System.Drawing.SystemColors.Window;
            this.cboGubun.DisplayLayout.Override.CardAreaAppearance = appearance130;
            appearance131.BorderColor = System.Drawing.Color.Silver;
            appearance131.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboGubun.DisplayLayout.Override.CellAppearance = appearance131;
            this.cboGubun.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboGubun.DisplayLayout.Override.CellPadding = 0;
            appearance132.BackColor = System.Drawing.SystemColors.Control;
            appearance132.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance132.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance132.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance132.BorderColor = System.Drawing.SystemColors.Window;
            this.cboGubun.DisplayLayout.Override.GroupByRowAppearance = appearance132;
            appearance133.TextHAlignAsString = "Left";
            this.cboGubun.DisplayLayout.Override.HeaderAppearance = appearance133;
            this.cboGubun.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboGubun.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance134.BackColor = System.Drawing.SystemColors.Window;
            appearance134.BorderColor = System.Drawing.Color.Silver;
            this.cboGubun.DisplayLayout.Override.RowAppearance = appearance134;
            this.cboGubun.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance135.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance135.FontData.BoldAsString = "True";
            this.cboGubun.DisplayLayout.Override.SelectedRowAppearance = appearance135;
            appearance136.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboGubun.DisplayLayout.Override.TemplateAddRowAppearance = appearance136;
            this.cboGubun.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboGubun.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboGubun.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboGubun.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboGubun.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboGubun.Location = new System.Drawing.Point(598, 13);
            this.cboGubun.MajorCode = "Furnace_Mat";
            this.cboGubun.Name = "cboGubun";
            this.cboGubun.ShowDefaultValue = false;
            this.cboGubun.Size = new System.Drawing.Size(160, 24);
            this.cboGubun.TabIndex = 4;
            this.cboGubun.Text = "ALL";
            // 
            // cboDaynight_H
            // 
            appearance17.FontData.Name = "맑은 고딕";
            appearance17.FontData.SizeInPoints = 9F;
            this.cboDaynight_H.Appearance = appearance17;
            this.cboDaynight_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboDaynight_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboDaynight_H.DbConfig = null;
            this.cboDaynight_H.DefaultValue = "ALL";
            appearance18.BackColor = System.Drawing.SystemColors.Window;
            appearance18.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboDaynight_H.DisplayLayout.Appearance = appearance18;
            this.cboDaynight_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboDaynight_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboDaynight_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance19.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance19.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance19.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance19.BorderColor = System.Drawing.SystemColors.Window;
            this.cboDaynight_H.DisplayLayout.GroupByBox.Appearance = appearance19;
            appearance20.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboDaynight_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance20;
            this.cboDaynight_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance21.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance21.BackColor2 = System.Drawing.SystemColors.Control;
            appearance21.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance21.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboDaynight_H.DisplayLayout.GroupByBox.PromptAppearance = appearance21;
            this.cboDaynight_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboDaynight_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboDaynight_H.DisplayLayout.Override.ActiveCellAppearance = appearance1;
            appearance23.BackColor = System.Drawing.SystemColors.Highlight;
            appearance23.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboDaynight_H.DisplayLayout.Override.ActiveRowAppearance = appearance23;
            appearance24.FontData.BoldAsString = "True";
            this.cboDaynight_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance24;
            this.cboDaynight_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboDaynight_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboDaynight_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance25.BackColor = System.Drawing.SystemColors.Window;
            this.cboDaynight_H.DisplayLayout.Override.CardAreaAppearance = appearance25;
            appearance26.BorderColor = System.Drawing.Color.Silver;
            appearance26.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboDaynight_H.DisplayLayout.Override.CellAppearance = appearance26;
            this.cboDaynight_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboDaynight_H.DisplayLayout.Override.CellPadding = 0;
            appearance27.BackColor = System.Drawing.SystemColors.Control;
            appearance27.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance27.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance27.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance27.BorderColor = System.Drawing.SystemColors.Window;
            this.cboDaynight_H.DisplayLayout.Override.GroupByRowAppearance = appearance27;
            appearance28.TextHAlignAsString = "Left";
            this.cboDaynight_H.DisplayLayout.Override.HeaderAppearance = appearance28;
            this.cboDaynight_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboDaynight_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance29.BackColor = System.Drawing.SystemColors.Window;
            appearance29.BorderColor = System.Drawing.Color.Silver;
            this.cboDaynight_H.DisplayLayout.Override.RowAppearance = appearance29;
            this.cboDaynight_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance30.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance30.FontData.BoldAsString = "True";
            this.cboDaynight_H.DisplayLayout.Override.SelectedRowAppearance = appearance30;
            appearance31.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboDaynight_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance31;
            this.cboDaynight_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboDaynight_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboDaynight_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboDaynight_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboDaynight_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboDaynight_H.Location = new System.Drawing.Point(1135, 17);
            this.cboDaynight_H.MajorCode = "DAYNIGHT";
            this.cboDaynight_H.Name = "cboDaynight_H";
            this.cboDaynight_H.ShowDefaultValue = false;
            this.cboDaynight_H.Size = new System.Drawing.Size(120, 24);
            this.cboDaynight_H.TabIndex = 219;
            this.cboDaynight_H.Text = "ALL";
            this.cboDaynight_H.Visible = false;
            // 
            // CboShiftGB
            // 
            this.CboShiftGB.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboShiftGB.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.CboShiftGB.DbConfig = null;
            this.CboShiftGB.DefaultValue = "ALL";
            appearance52.BackColor = System.Drawing.SystemColors.Window;
            appearance52.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.CboShiftGB.DisplayLayout.Appearance = appearance52;
            this.CboShiftGB.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.CboShiftGB.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboShiftGB.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance53.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance53.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance53.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance53.BorderColor = System.Drawing.SystemColors.Window;
            this.CboShiftGB.DisplayLayout.GroupByBox.Appearance = appearance53;
            appearance54.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboShiftGB.DisplayLayout.GroupByBox.BandLabelAppearance = appearance54;
            this.CboShiftGB.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance55.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance55.BackColor2 = System.Drawing.SystemColors.Control;
            appearance55.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance55.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboShiftGB.DisplayLayout.GroupByBox.PromptAppearance = appearance55;
            this.CboShiftGB.DisplayLayout.MaxColScrollRegions = 1;
            this.CboShiftGB.DisplayLayout.MaxRowScrollRegions = 1;
            appearance56.BackColor = System.Drawing.SystemColors.Window;
            appearance56.ForeColor = System.Drawing.SystemColors.ControlText;
            this.CboShiftGB.DisplayLayout.Override.ActiveCellAppearance = appearance56;
            appearance57.BackColor = System.Drawing.SystemColors.Highlight;
            appearance57.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.CboShiftGB.DisplayLayout.Override.ActiveRowAppearance = appearance57;
            appearance58.FontData.BoldAsString = "True";
            this.CboShiftGB.DisplayLayout.Override.ActiveRowCellAppearance = appearance58;
            this.CboShiftGB.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboShiftGB.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboShiftGB.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance59.BackColor = System.Drawing.SystemColors.Window;
            this.CboShiftGB.DisplayLayout.Override.CardAreaAppearance = appearance59;
            appearance60.BorderColor = System.Drawing.Color.Silver;
            appearance60.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.CboShiftGB.DisplayLayout.Override.CellAppearance = appearance60;
            this.CboShiftGB.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.CboShiftGB.DisplayLayout.Override.CellPadding = 0;
            appearance61.BackColor = System.Drawing.SystemColors.Control;
            appearance61.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance61.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance61.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance61.BorderColor = System.Drawing.SystemColors.Window;
            this.CboShiftGB.DisplayLayout.Override.GroupByRowAppearance = appearance61;
            appearance62.TextHAlignAsString = "Left";
            this.CboShiftGB.DisplayLayout.Override.HeaderAppearance = appearance62;
            this.CboShiftGB.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.CboShiftGB.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance63.BackColor = System.Drawing.SystemColors.Window;
            appearance63.BorderColor = System.Drawing.Color.Silver;
            this.CboShiftGB.DisplayLayout.Override.RowAppearance = appearance63;
            this.CboShiftGB.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance64.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance64.FontData.BoldAsString = "True";
            this.CboShiftGB.DisplayLayout.Override.SelectedRowAppearance = appearance64;
            appearance65.BackColor = System.Drawing.SystemColors.ControlLight;
            this.CboShiftGB.DisplayLayout.Override.TemplateAddRowAppearance = appearance65;
            this.CboShiftGB.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.CboShiftGB.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.CboShiftGB.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.CboShiftGB.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.CboShiftGB.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.CboShiftGB.Location = new System.Drawing.Point(860, 172);
            this.CboShiftGB.MajorCode = "SHIFTGB";
            this.CboShiftGB.Name = "CboShiftGB";
            this.CboShiftGB.ShowDefaultValue = false;
            this.CboShiftGB.Size = new System.Drawing.Size(157, 25);
            this.CboShiftGB.TabIndex = 120;
            this.CboShiftGB.Text = "ALL";
            // 
            // CboDayNight
            // 
            this.CboDayNight.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboDayNight.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.CboDayNight.DbConfig = null;
            this.CboDayNight.DefaultValue = "ALL";
            appearance66.BackColor = System.Drawing.SystemColors.Window;
            appearance66.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.CboDayNight.DisplayLayout.Appearance = appearance66;
            this.CboDayNight.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.CboDayNight.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboDayNight.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance67.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance67.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance67.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance67.BorderColor = System.Drawing.SystemColors.Window;
            this.CboDayNight.DisplayLayout.GroupByBox.Appearance = appearance67;
            appearance68.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboDayNight.DisplayLayout.GroupByBox.BandLabelAppearance = appearance68;
            this.CboDayNight.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance69.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance69.BackColor2 = System.Drawing.SystemColors.Control;
            appearance69.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance69.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboDayNight.DisplayLayout.GroupByBox.PromptAppearance = appearance69;
            this.CboDayNight.DisplayLayout.MaxColScrollRegions = 1;
            this.CboDayNight.DisplayLayout.MaxRowScrollRegions = 1;
            appearance70.BackColor = System.Drawing.SystemColors.Window;
            appearance70.ForeColor = System.Drawing.SystemColors.ControlText;
            this.CboDayNight.DisplayLayout.Override.ActiveCellAppearance = appearance70;
            appearance71.BackColor = System.Drawing.SystemColors.Highlight;
            appearance71.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.CboDayNight.DisplayLayout.Override.ActiveRowAppearance = appearance71;
            appearance72.FontData.BoldAsString = "True";
            this.CboDayNight.DisplayLayout.Override.ActiveRowCellAppearance = appearance72;
            this.CboDayNight.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboDayNight.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboDayNight.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance73.BackColor = System.Drawing.SystemColors.Window;
            this.CboDayNight.DisplayLayout.Override.CardAreaAppearance = appearance73;
            appearance74.BorderColor = System.Drawing.Color.Silver;
            appearance74.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.CboDayNight.DisplayLayout.Override.CellAppearance = appearance74;
            this.CboDayNight.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.CboDayNight.DisplayLayout.Override.CellPadding = 0;
            appearance75.BackColor = System.Drawing.SystemColors.Control;
            appearance75.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance75.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance75.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance75.BorderColor = System.Drawing.SystemColors.Window;
            this.CboDayNight.DisplayLayout.Override.GroupByRowAppearance = appearance75;
            appearance76.TextHAlignAsString = "Left";
            this.CboDayNight.DisplayLayout.Override.HeaderAppearance = appearance76;
            this.CboDayNight.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.CboDayNight.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance77.BackColor = System.Drawing.SystemColors.Window;
            appearance77.BorderColor = System.Drawing.Color.Silver;
            this.CboDayNight.DisplayLayout.Override.RowAppearance = appearance77;
            this.CboDayNight.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance78.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance78.FontData.BoldAsString = "True";
            this.CboDayNight.DisplayLayout.Override.SelectedRowAppearance = appearance78;
            appearance79.BackColor = System.Drawing.SystemColors.ControlLight;
            this.CboDayNight.DisplayLayout.Override.TemplateAddRowAppearance = appearance79;
            this.CboDayNight.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.CboDayNight.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.CboDayNight.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.CboDayNight.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.CboDayNight.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.CboDayNight.Location = new System.Drawing.Point(657, 172);
            this.CboDayNight.MajorCode = "DAYNIGHT";
            this.CboDayNight.Name = "CboDayNight";
            this.CboDayNight.ShowDefaultValue = false;
            this.CboDayNight.Size = new System.Drawing.Size(159, 25);
            this.CboDayNight.TabIndex = 119;
            this.CboDayNight.Text = "ALL";
            // 
            // CboWorkcentercode
            // 
            this.CboWorkcentercode.AutoSize = false;
            this.CboWorkcentercode.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboWorkcentercode.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.CboWorkcentercode.DataMember = "dTable1";
            this.CboWorkcentercode.DbConfig = null;
            this.CboWorkcentercode.DefaultValue = "ALL";
            appearance80.BackColor = System.Drawing.SystemColors.Window;
            appearance80.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.CboWorkcentercode.DisplayLayout.Appearance = appearance80;
            this.CboWorkcentercode.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn5.Header.VisiblePosition = 0;
            ultraGridColumn6.Header.VisiblePosition = 1;
            ultraGridBand1.Columns.AddRange(new object[] {
            ultraGridColumn5,
            ultraGridColumn6});
            this.CboWorkcentercode.DisplayLayout.BandsSerializer.Add(ultraGridBand1);
            this.CboWorkcentercode.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboWorkcentercode.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance81.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance81.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance81.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance81.BorderColor = System.Drawing.SystemColors.Window;
            this.CboWorkcentercode.DisplayLayout.GroupByBox.Appearance = appearance81;
            appearance82.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboWorkcentercode.DisplayLayout.GroupByBox.BandLabelAppearance = appearance82;
            this.CboWorkcentercode.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance83.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance83.BackColor2 = System.Drawing.SystemColors.Control;
            appearance83.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance83.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboWorkcentercode.DisplayLayout.GroupByBox.PromptAppearance = appearance83;
            this.CboWorkcentercode.DisplayLayout.MaxColScrollRegions = 1;
            this.CboWorkcentercode.DisplayLayout.MaxRowScrollRegions = 1;
            appearance84.BackColor = System.Drawing.SystemColors.Window;
            appearance84.ForeColor = System.Drawing.SystemColors.ControlText;
            this.CboWorkcentercode.DisplayLayout.Override.ActiveCellAppearance = appearance84;
            appearance85.BackColor = System.Drawing.SystemColors.Highlight;
            appearance85.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.CboWorkcentercode.DisplayLayout.Override.ActiveRowAppearance = appearance85;
            appearance86.FontData.BoldAsString = "True";
            this.CboWorkcentercode.DisplayLayout.Override.ActiveRowCellAppearance = appearance86;
            this.CboWorkcentercode.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboWorkcentercode.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboWorkcentercode.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance87.BackColor = System.Drawing.SystemColors.Window;
            this.CboWorkcentercode.DisplayLayout.Override.CardAreaAppearance = appearance87;
            appearance88.BorderColor = System.Drawing.Color.Silver;
            appearance88.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.CboWorkcentercode.DisplayLayout.Override.CellAppearance = appearance88;
            this.CboWorkcentercode.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.CboWorkcentercode.DisplayLayout.Override.CellPadding = 0;
            appearance89.BackColor = System.Drawing.SystemColors.Control;
            appearance89.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance89.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance89.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance89.BorderColor = System.Drawing.SystemColors.Window;
            this.CboWorkcentercode.DisplayLayout.Override.GroupByRowAppearance = appearance89;
            appearance90.TextHAlignAsString = "Left";
            this.CboWorkcentercode.DisplayLayout.Override.HeaderAppearance = appearance90;
            this.CboWorkcentercode.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.CboWorkcentercode.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance91.BackColor = System.Drawing.SystemColors.Window;
            appearance91.BorderColor = System.Drawing.Color.Silver;
            this.CboWorkcentercode.DisplayLayout.Override.RowAppearance = appearance91;
            this.CboWorkcentercode.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance92.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance92.FontData.BoldAsString = "True";
            this.CboWorkcentercode.DisplayLayout.Override.SelectedRowAppearance = appearance92;
            appearance93.BackColor = System.Drawing.SystemColors.ControlLight;
            this.CboWorkcentercode.DisplayLayout.Override.TemplateAddRowAppearance = appearance93;
            this.CboWorkcentercode.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.CboWorkcentercode.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.CboWorkcentercode.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.CboWorkcentercode.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.CboWorkcentercode.DisplayMember = "WorkCenterName";
            this.CboWorkcentercode.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.CboWorkcentercode.Location = new System.Drawing.Point(462, 172);
            this.CboWorkcentercode.Name = "CboWorkcentercode";
            this.CboWorkcentercode.Opcode = null;
            this.CboWorkcentercode.PlantCode = null;
            this.CboWorkcentercode.ShowDefaultValue = false;
            this.CboWorkcentercode.Size = new System.Drawing.Size(160, 26);
            this.CboWorkcentercode.TabIndex = 117;
            this.CboWorkcentercode.Text = "ALL";
            this.CboWorkcentercode.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.CboWorkcentercode.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.CboWorkcentercode.ValueMember = "WorkCenterCode";
            // 
            // CboLineCode
            // 
            this.CboLineCode.AutoSize = false;
            this.CboLineCode.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboLineCode.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.CboLineCode.DataMember = "dTable1";
            this.CboLineCode.DbConfig = null;
            this.CboLineCode.DefaultValue = "ALL";
            appearance94.BackColor = System.Drawing.SystemColors.Window;
            appearance94.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.CboLineCode.DisplayLayout.Appearance = appearance94;
            this.CboLineCode.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn1.Header.VisiblePosition = 0;
            ultraGridColumn2.Header.VisiblePosition = 1;
            ultraGridBand2.Columns.AddRange(new object[] {
            ultraGridColumn1,
            ultraGridColumn2});
            this.CboLineCode.DisplayLayout.BandsSerializer.Add(ultraGridBand2);
            this.CboLineCode.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboLineCode.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance95.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance95.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance95.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance95.BorderColor = System.Drawing.SystemColors.Window;
            this.CboLineCode.DisplayLayout.GroupByBox.Appearance = appearance95;
            appearance96.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboLineCode.DisplayLayout.GroupByBox.BandLabelAppearance = appearance96;
            this.CboLineCode.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance97.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance97.BackColor2 = System.Drawing.SystemColors.Control;
            appearance97.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance97.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboLineCode.DisplayLayout.GroupByBox.PromptAppearance = appearance97;
            this.CboLineCode.DisplayLayout.MaxColScrollRegions = 1;
            this.CboLineCode.DisplayLayout.MaxRowScrollRegions = 1;
            appearance98.BackColor = System.Drawing.SystemColors.Window;
            appearance98.ForeColor = System.Drawing.SystemColors.ControlText;
            this.CboLineCode.DisplayLayout.Override.ActiveCellAppearance = appearance98;
            appearance99.BackColor = System.Drawing.SystemColors.Highlight;
            appearance99.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.CboLineCode.DisplayLayout.Override.ActiveRowAppearance = appearance99;
            appearance100.FontData.BoldAsString = "True";
            this.CboLineCode.DisplayLayout.Override.ActiveRowCellAppearance = appearance100;
            this.CboLineCode.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboLineCode.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboLineCode.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance101.BackColor = System.Drawing.SystemColors.Window;
            this.CboLineCode.DisplayLayout.Override.CardAreaAppearance = appearance101;
            appearance102.BorderColor = System.Drawing.Color.Silver;
            appearance102.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.CboLineCode.DisplayLayout.Override.CellAppearance = appearance102;
            this.CboLineCode.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.CboLineCode.DisplayLayout.Override.CellPadding = 0;
            appearance103.BackColor = System.Drawing.SystemColors.Control;
            appearance103.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance103.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance103.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance103.BorderColor = System.Drawing.SystemColors.Window;
            this.CboLineCode.DisplayLayout.Override.GroupByRowAppearance = appearance103;
            appearance104.TextHAlignAsString = "Left";
            this.CboLineCode.DisplayLayout.Override.HeaderAppearance = appearance104;
            this.CboLineCode.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.CboLineCode.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance105.BackColor = System.Drawing.SystemColors.Window;
            appearance105.BorderColor = System.Drawing.Color.Silver;
            this.CboLineCode.DisplayLayout.Override.RowAppearance = appearance105;
            this.CboLineCode.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance106.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance106.FontData.BoldAsString = "True";
            this.CboLineCode.DisplayLayout.Override.SelectedRowAppearance = appearance106;
            appearance107.BackColor = System.Drawing.SystemColors.ControlLight;
            this.CboLineCode.DisplayLayout.Override.TemplateAddRowAppearance = appearance107;
            this.CboLineCode.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.CboLineCode.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.CboLineCode.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.CboLineCode.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.CboLineCode.DisplayMember = "LineName";
            this.CboLineCode.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.CboLineCode.Location = new System.Drawing.Point(270, 172);
            this.CboLineCode.Name = "CboLineCode";
            this.CboLineCode.ShowDefaultValue = false;
            this.CboLineCode.Size = new System.Drawing.Size(162, 26);
            this.CboLineCode.TabIndex = 116;
            this.CboLineCode.Text = "ALL";
            this.CboLineCode.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.CboLineCode.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.CboLineCode.ValueMember = "LineCode";
            // 
            // CboOpcode
            // 
            this.CboOpcode.AutoSize = false;
            this.CboOpcode.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboOpcode.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.CboOpcode.DataMember = "dTable1";
            this.CboOpcode.DbConfig = null;
            this.CboOpcode.DefaultValue = "ALL";
            appearance108.BackColor = System.Drawing.SystemColors.Window;
            appearance108.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.CboOpcode.DisplayLayout.Appearance = appearance108;
            this.CboOpcode.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn13.Header.VisiblePosition = 0;
            ultraGridColumn14.Header.VisiblePosition = 1;
            ultraGridBand3.Columns.AddRange(new object[] {
            ultraGridColumn13,
            ultraGridColumn14});
            this.CboOpcode.DisplayLayout.BandsSerializer.Add(ultraGridBand3);
            this.CboOpcode.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.CboOpcode.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance109.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance109.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance109.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance109.BorderColor = System.Drawing.SystemColors.Window;
            this.CboOpcode.DisplayLayout.GroupByBox.Appearance = appearance109;
            appearance110.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboOpcode.DisplayLayout.GroupByBox.BandLabelAppearance = appearance110;
            this.CboOpcode.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance111.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance111.BackColor2 = System.Drawing.SystemColors.Control;
            appearance111.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance111.ForeColor = System.Drawing.SystemColors.GrayText;
            this.CboOpcode.DisplayLayout.GroupByBox.PromptAppearance = appearance111;
            this.CboOpcode.DisplayLayout.MaxColScrollRegions = 1;
            this.CboOpcode.DisplayLayout.MaxRowScrollRegions = 1;
            appearance112.BackColor = System.Drawing.SystemColors.Window;
            appearance112.ForeColor = System.Drawing.SystemColors.ControlText;
            this.CboOpcode.DisplayLayout.Override.ActiveCellAppearance = appearance112;
            appearance113.BackColor = System.Drawing.SystemColors.Highlight;
            appearance113.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.CboOpcode.DisplayLayout.Override.ActiveRowAppearance = appearance113;
            appearance114.FontData.BoldAsString = "True";
            this.CboOpcode.DisplayLayout.Override.ActiveRowCellAppearance = appearance114;
            this.CboOpcode.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboOpcode.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.CboOpcode.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance115.BackColor = System.Drawing.SystemColors.Window;
            this.CboOpcode.DisplayLayout.Override.CardAreaAppearance = appearance115;
            appearance116.BorderColor = System.Drawing.Color.Silver;
            appearance116.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.CboOpcode.DisplayLayout.Override.CellAppearance = appearance116;
            this.CboOpcode.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.CboOpcode.DisplayLayout.Override.CellPadding = 0;
            appearance117.BackColor = System.Drawing.SystemColors.Control;
            appearance117.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance117.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance117.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance117.BorderColor = System.Drawing.SystemColors.Window;
            this.CboOpcode.DisplayLayout.Override.GroupByRowAppearance = appearance117;
            appearance118.TextHAlignAsString = "Left";
            this.CboOpcode.DisplayLayout.Override.HeaderAppearance = appearance118;
            this.CboOpcode.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.CboOpcode.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance119.BackColor = System.Drawing.SystemColors.Window;
            appearance119.BorderColor = System.Drawing.Color.Silver;
            this.CboOpcode.DisplayLayout.Override.RowAppearance = appearance119;
            this.CboOpcode.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance120.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance120.FontData.BoldAsString = "True";
            this.CboOpcode.DisplayLayout.Override.SelectedRowAppearance = appearance120;
            appearance121.BackColor = System.Drawing.SystemColors.ControlLight;
            this.CboOpcode.DisplayLayout.Override.TemplateAddRowAppearance = appearance121;
            this.CboOpcode.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.CboOpcode.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.CboOpcode.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.CboOpcode.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.CboOpcode.DisplayMember = "OPName";
            this.CboOpcode.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.CboOpcode.Location = new System.Drawing.Point(50, 172);
            this.CboOpcode.Name = "CboOpcode";
            this.CboOpcode.ShowDefaultValue = false;
            this.CboOpcode.Size = new System.Drawing.Size(160, 26);
            this.CboOpcode.TabIndex = 112;
            this.CboOpcode.Text = "ALL";
            this.CboOpcode.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.CboOpcode.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.CboOpcode.ValueMember = "OPCode";
            // 
            // sLabel2
            // 
            appearance22.TextHAlignAsString = "Right";
            appearance22.TextVAlignAsString = "Middle";
            this.sLabel2.Appearance = appearance22;
            this.sLabel2.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.sLabel2.DbField = "cboUseFlag";
            this.sLabel2.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.sLabel2.Location = new System.Drawing.Point(12, 13);
            this.sLabel2.Name = "sLabel2";
            this.sLabel2.Size = new System.Drawing.Size(52, 26);
            this.sLabel2.TabIndex = 548;
            this.sLabel2.Text = "사업장";
            // 
            // cboPlantCode_H
            // 
            appearance2.FontData.Name = "맑은 고딕";
            appearance2.FontData.SizeInPoints = 9F;
            this.cboPlantCode_H.Appearance = appearance2;
            this.cboPlantCode_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboPlantCode_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboPlantCode_H.DbConfig = null;
            this.cboPlantCode_H.DefaultValue = "ALL";
            appearance35.BackColor = System.Drawing.SystemColors.Window;
            appearance35.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboPlantCode_H.DisplayLayout.Appearance = appearance35;
            this.cboPlantCode_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboPlantCode_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboPlantCode_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance36.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance36.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance36.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance36.BorderColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.Appearance = appearance36;
            appearance37.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance37;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance6.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance6.BackColor2 = System.Drawing.SystemColors.Control;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.PromptAppearance = appearance6;
            this.cboPlantCode_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboPlantCode_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            appearance7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboPlantCode_H.DisplayLayout.Override.ActiveCellAppearance = appearance7;
            appearance8.BackColor = System.Drawing.SystemColors.Highlight;
            appearance8.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboPlantCode_H.DisplayLayout.Override.ActiveRowAppearance = appearance8;
            appearance9.FontData.BoldAsString = "True";
            this.cboPlantCode_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance9;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.Override.CardAreaAppearance = appearance10;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            appearance11.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboPlantCode_H.DisplayLayout.Override.CellAppearance = appearance11;
            this.cboPlantCode_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboPlantCode_H.DisplayLayout.Override.CellPadding = 0;
            appearance12.BackColor = System.Drawing.SystemColors.Control;
            appearance12.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance12.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance12.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance12.BorderColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.Override.GroupByRowAppearance = appearance12;
            appearance13.TextHAlignAsString = "Left";
            this.cboPlantCode_H.DisplayLayout.Override.HeaderAppearance = appearance13;
            this.cboPlantCode_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboPlantCode_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            this.cboPlantCode_H.DisplayLayout.Override.RowAppearance = appearance14;
            this.cboPlantCode_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance15.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance15.FontData.BoldAsString = "True";
            this.cboPlantCode_H.DisplayLayout.Override.SelectedRowAppearance = appearance15;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboPlantCode_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance16;
            this.cboPlantCode_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboPlantCode_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboPlantCode_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboPlantCode_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboPlantCode_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboPlantCode_H.Location = new System.Drawing.Point(70, 14);
            this.cboPlantCode_H.MajorCode = "PLANTCODE";
            this.cboPlantCode_H.Name = "cboPlantCode_H";
            this.cboPlantCode_H.ShowDefaultValue = false;
            this.cboPlantCode_H.Size = new System.Drawing.Size(119, 24);
            this.cboPlantCode_H.TabIndex = 557;
            this.cboPlantCode_H.Text = "ALL";
            // 
            // PP3700
            // 
            this.ClientSize = new System.Drawing.Size(1263, 597);
            this.Name = "PP3700";
            this.Text = "일일생산실적관리(Lot별)";
            this.Load += new System.EventHandler(this.PP3700_Load);
            ((System.ComponentModel.ISupportInitialize)(this.gbxHeader)).EndInit();
            this.gbxHeader.ResumeLayout(false);
            this.gbxHeader.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gbxBody)).EndInit();
            this.gbxBody.ResumeLayout(false);
            this.gbxBody.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grid1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboStartdate_H)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboEnddate_H)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboGubun)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboDaynight_H)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboShiftGB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboDayNight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboWorkcentercode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboLineCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CboOpcode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboPlantCode_H)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Control.Grid grid1;
        private Control.SCodeNMComboBox CboShiftGB;
        private Control.SCodeNMComboBox CboDayNight;
        private Control.ScboGetWorkCenterCode CboWorkcentercode;
        private Control.ScboGetLineCode CboLineCode;
        private Control.ScboGetOPCode CboOpcode;
        private System.Windows.Forms.TextBox txtLineName;
        private System.Windows.Forms.TextBox txtOPCode;
        private System.Windows.Forms.TextBox txtOPName;
        private Control.SLabel sLabel6;
        private Control.SCodeNMComboBox cboGubun;
        private Control.SCodeNMComboBox cboDaynight_H;
        private Infragistics.Win.UltraWinSchedule.UltraCalendarCombo CboStartdate_H;
        private Infragistics.Win.UltraWinSchedule.UltraCalendarCombo CboEnddate_H;
        private Infragistics.Win.Misc.UltraLabel ultraLabel4;
        private Control.SLabel sLabel5;
        private Control.SLabel lblLineCode;
        private Control.SLabel lblOPCode;
        private Control.SLabel sLabel1;
        private Control.SLabel lblUseFlag;
        private Control.SLabel sLabel2;
        private Control.SCodeNMComboBox cboPlantCode_H;

    }
}
