namespace SAMMI.BM
{
    partial class BM1100
    {
        /// <summary>
        /// 필수 디자이너 변수입니다.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 사용 중인 모든 리소스를 정리합니다.
        /// </summary>
        /// <param name="disposing">관리되는 리소스를 삭제해야 하면 true이고, 그렇지 않으면 false입니다.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form 디자이너에서 생성한 코드

        /// <summary>
        /// 디자이너 지원에 필요한 메서드입니다.
        /// 이 메서드의 내용을 코드 편집기로 수정하지 마십시오.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance65 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance66 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance67 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance68 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance69 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance70 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance71 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance72 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance73 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance74 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance75 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance76 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance77 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance78 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance79 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance80 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance81 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance82 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance83 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance84 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance85 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance86 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance87 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance88 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance89 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance90 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance105 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance106 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance107 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance108 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance109 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance110 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance111 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance112 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance113 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance114 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance115 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance116 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance117 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance118 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance91 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance92 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance93 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance94 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance95 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance96 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance97 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance98 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance99 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance100 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance101 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance102 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance103 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance104 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance119 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance133 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance134 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance135 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance131 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance132 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance120 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance121 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance122 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance123 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance124 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance125 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance126 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance127 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance128 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance129 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance130 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            this.cboStopType = new SAMMI.Control.SCodeNMComboBox();
            this.cboSTOPCLASS = new SAMMI.Control.SCodeNMComboBox();
            this.cboYesNo = new SAMMI.Control.SCodeNMComboBox();
            this.cboUSEFLAG = new SAMMI.Control.SCodeNMComboBox();
            this.grid1 = new SAMMI.Control.Grid(this.components);
            this.lblStopClass = new SAMMI.Control.SLabel();
            this.lblStopType = new SAMMI.Control.SLabel();
            this.lblUseFlag = new SAMMI.Control.SLabel();
            this.txtPlantCode = new System.Windows.Forms.TextBox();
            this.lblPlantCode = new SAMMI.Control.SLabel();
            this.txtOPCode = new System.Windows.Forms.TextBox();
            this.lblWorkCenterCode_H = new SAMMI.Control.SLabel();
            this.txtStopCode = new System.Windows.Forms.TextBox();
            this.sLabel1 = new SAMMI.Control.SLabel();
            this.cboUseFlag_H = new SAMMI.Control.SCodeNMComboBox();
            this.cboStopClass_H = new SAMMI.Control.SCodeNMComboBox();
            this.cboStopType_H = new SAMMI.Control.SCodeNMComboBox();
            this.txtStopName = new System.Windows.Forms.TextBox();
            this.txtOPName = new System.Windows.Forms.TextBox();
            this.cboPlantCode_H = new SAMMI.Control.SCodeNMComboBox();
            this.sLabel5 = new SAMMI.Control.SLabel();
            ((System.ComponentModel.ISupportInitialize)(this.gbxHeader)).BeginInit();
            this.gbxHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gbxBody)).BeginInit();
            this.gbxBody.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cboStopType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboSTOPCLASS)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboYesNo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboUSEFLAG)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grid1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboUseFlag_H)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboStopClass_H)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboStopType_H)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboPlantCode_H)).BeginInit();
            this.SuspendLayout();
            // 
            // gbxHeader
            // 
            this.gbxHeader.ContentPadding.Bottom = 2;
            this.gbxHeader.ContentPadding.Left = 2;
            this.gbxHeader.ContentPadding.Right = 2;
            this.gbxHeader.ContentPadding.Top = 4;
            this.gbxHeader.Controls.Add(this.cboPlantCode_H);
            this.gbxHeader.Controls.Add(this.sLabel5);
            this.gbxHeader.Controls.Add(this.txtStopName);
            this.gbxHeader.Controls.Add(this.txtOPName);
            this.gbxHeader.Controls.Add(this.cboStopType_H);
            this.gbxHeader.Controls.Add(this.cboStopClass_H);
            this.gbxHeader.Controls.Add(this.cboUseFlag_H);
            this.gbxHeader.Controls.Add(this.txtStopCode);
            this.gbxHeader.Controls.Add(this.sLabel1);
            this.gbxHeader.Controls.Add(this.txtOPCode);
            this.gbxHeader.Controls.Add(this.lblWorkCenterCode_H);
            this.gbxHeader.Controls.Add(this.lblStopClass);
            this.gbxHeader.Controls.Add(this.lblStopType);
            this.gbxHeader.Controls.Add(this.lblUseFlag);
            this.gbxHeader.Size = new System.Drawing.Size(1136, 74);
            // 
            // gbxBody
            // 
            this.gbxBody.ContentPadding.Bottom = 4;
            this.gbxBody.ContentPadding.Left = 4;
            this.gbxBody.ContentPadding.Right = 4;
            this.gbxBody.ContentPadding.Top = 6;
            this.gbxBody.Controls.Add(this.grid1);
            this.gbxBody.Controls.Add(this.cboStopType);
            this.gbxBody.Controls.Add(this.cboSTOPCLASS);
            this.gbxBody.Controls.Add(this.cboUSEFLAG);
            this.gbxBody.Controls.Add(this.cboYesNo);
            this.gbxBody.Controls.Add(this.txtPlantCode);
            this.gbxBody.Controls.Add(this.lblPlantCode);
            this.gbxBody.Location = new System.Drawing.Point(0, 74);
            this.gbxBody.Size = new System.Drawing.Size(1136, 704);
            // 
            // cboStopType
            // 
            this.cboStopType.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboStopType.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboStopType.DbConfig = null;
            this.cboStopType.DefaultValue = "";
            appearance63.BackColor = System.Drawing.SystemColors.Window;
            appearance63.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboStopType.DisplayLayout.Appearance = appearance63;
            this.cboStopType.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboStopType.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboStopType.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance64.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance64.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance64.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance64.BorderColor = System.Drawing.SystemColors.Window;
            this.cboStopType.DisplayLayout.GroupByBox.Appearance = appearance64;
            appearance65.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboStopType.DisplayLayout.GroupByBox.BandLabelAppearance = appearance65;
            this.cboStopType.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance66.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance66.BackColor2 = System.Drawing.SystemColors.Control;
            appearance66.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance66.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboStopType.DisplayLayout.GroupByBox.PromptAppearance = appearance66;
            this.cboStopType.DisplayLayout.MaxColScrollRegions = 1;
            this.cboStopType.DisplayLayout.MaxRowScrollRegions = 1;
            appearance67.BackColor = System.Drawing.SystemColors.Window;
            appearance67.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboStopType.DisplayLayout.Override.ActiveCellAppearance = appearance67;
            appearance68.BackColor = System.Drawing.SystemColors.Highlight;
            appearance68.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboStopType.DisplayLayout.Override.ActiveRowAppearance = appearance68;
            appearance69.FontData.BoldAsString = "True";
            this.cboStopType.DisplayLayout.Override.ActiveRowCellAppearance = appearance69;
            this.cboStopType.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboStopType.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboStopType.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance70.BackColor = System.Drawing.SystemColors.Window;
            this.cboStopType.DisplayLayout.Override.CardAreaAppearance = appearance70;
            appearance71.BorderColor = System.Drawing.Color.Silver;
            appearance71.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboStopType.DisplayLayout.Override.CellAppearance = appearance71;
            this.cboStopType.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboStopType.DisplayLayout.Override.CellPadding = 0;
            appearance72.BackColor = System.Drawing.SystemColors.Control;
            appearance72.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance72.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance72.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance72.BorderColor = System.Drawing.SystemColors.Window;
            this.cboStopType.DisplayLayout.Override.GroupByRowAppearance = appearance72;
            appearance73.TextHAlignAsString = "Left";
            this.cboStopType.DisplayLayout.Override.HeaderAppearance = appearance73;
            this.cboStopType.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboStopType.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance74.BackColor = System.Drawing.SystemColors.Window;
            appearance74.BorderColor = System.Drawing.Color.Silver;
            this.cboStopType.DisplayLayout.Override.RowAppearance = appearance74;
            this.cboStopType.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance75.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance75.FontData.BoldAsString = "True";
            this.cboStopType.DisplayLayout.Override.SelectedRowAppearance = appearance75;
            appearance76.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboStopType.DisplayLayout.Override.TemplateAddRowAppearance = appearance76;
            this.cboStopType.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboStopType.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboStopType.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboStopType.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboStopType.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboStopType.Location = new System.Drawing.Point(96, 322);
            this.cboStopType.MajorCode = "STOPTYPE";
            this.cboStopType.Name = "cboStopType";
            this.cboStopType.ShowDefaultValue = false;
            this.cboStopType.Size = new System.Drawing.Size(130, 25);
            this.cboStopType.TabIndex = 11;
            // 
            // cboSTOPCLASS
            // 
            this.cboSTOPCLASS.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboSTOPCLASS.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboSTOPCLASS.DbConfig = null;
            this.cboSTOPCLASS.DefaultValue = "";
            appearance77.BackColor = System.Drawing.SystemColors.Window;
            appearance77.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboSTOPCLASS.DisplayLayout.Appearance = appearance77;
            this.cboSTOPCLASS.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboSTOPCLASS.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboSTOPCLASS.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance78.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance78.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance78.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance78.BorderColor = System.Drawing.SystemColors.Window;
            this.cboSTOPCLASS.DisplayLayout.GroupByBox.Appearance = appearance78;
            appearance79.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboSTOPCLASS.DisplayLayout.GroupByBox.BandLabelAppearance = appearance79;
            this.cboSTOPCLASS.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance80.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance80.BackColor2 = System.Drawing.SystemColors.Control;
            appearance80.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance80.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboSTOPCLASS.DisplayLayout.GroupByBox.PromptAppearance = appearance80;
            this.cboSTOPCLASS.DisplayLayout.MaxColScrollRegions = 1;
            this.cboSTOPCLASS.DisplayLayout.MaxRowScrollRegions = 1;
            appearance81.BackColor = System.Drawing.SystemColors.Window;
            appearance81.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboSTOPCLASS.DisplayLayout.Override.ActiveCellAppearance = appearance81;
            appearance82.BackColor = System.Drawing.SystemColors.Highlight;
            appearance82.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboSTOPCLASS.DisplayLayout.Override.ActiveRowAppearance = appearance82;
            appearance83.FontData.BoldAsString = "True";
            this.cboSTOPCLASS.DisplayLayout.Override.ActiveRowCellAppearance = appearance83;
            this.cboSTOPCLASS.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboSTOPCLASS.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboSTOPCLASS.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance84.BackColor = System.Drawing.SystemColors.Window;
            this.cboSTOPCLASS.DisplayLayout.Override.CardAreaAppearance = appearance84;
            appearance85.BorderColor = System.Drawing.Color.Silver;
            appearance85.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboSTOPCLASS.DisplayLayout.Override.CellAppearance = appearance85;
            this.cboSTOPCLASS.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboSTOPCLASS.DisplayLayout.Override.CellPadding = 0;
            appearance86.BackColor = System.Drawing.SystemColors.Control;
            appearance86.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance86.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance86.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance86.BorderColor = System.Drawing.SystemColors.Window;
            this.cboSTOPCLASS.DisplayLayout.Override.GroupByRowAppearance = appearance86;
            appearance87.TextHAlignAsString = "Left";
            this.cboSTOPCLASS.DisplayLayout.Override.HeaderAppearance = appearance87;
            this.cboSTOPCLASS.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboSTOPCLASS.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance88.BackColor = System.Drawing.SystemColors.Window;
            appearance88.BorderColor = System.Drawing.Color.Silver;
            this.cboSTOPCLASS.DisplayLayout.Override.RowAppearance = appearance88;
            this.cboSTOPCLASS.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance89.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance89.FontData.BoldAsString = "True";
            this.cboSTOPCLASS.DisplayLayout.Override.SelectedRowAppearance = appearance89;
            appearance90.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboSTOPCLASS.DisplayLayout.Override.TemplateAddRowAppearance = appearance90;
            this.cboSTOPCLASS.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboSTOPCLASS.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboSTOPCLASS.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboSTOPCLASS.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboSTOPCLASS.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboSTOPCLASS.Location = new System.Drawing.Point(465, 317);
            this.cboSTOPCLASS.MajorCode = "STOPCLASS";
            this.cboSTOPCLASS.Name = "cboSTOPCLASS";
            this.cboSTOPCLASS.ShowDefaultValue = false;
            this.cboSTOPCLASS.Size = new System.Drawing.Size(191, 25);
            this.cboSTOPCLASS.TabIndex = 12;
            this.cboSTOPCLASS.Text = "sCodeNMComboBox4";
            // 
            // cboYesNo
            // 
            this.cboYesNo.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboYesNo.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboYesNo.DbConfig = null;
            this.cboYesNo.DefaultValue = "";
            appearance105.BackColor = System.Drawing.SystemColors.Window;
            appearance105.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboYesNo.DisplayLayout.Appearance = appearance105;
            this.cboYesNo.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboYesNo.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboYesNo.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance106.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance106.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance106.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance106.BorderColor = System.Drawing.SystemColors.Window;
            this.cboYesNo.DisplayLayout.GroupByBox.Appearance = appearance106;
            appearance107.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboYesNo.DisplayLayout.GroupByBox.BandLabelAppearance = appearance107;
            this.cboYesNo.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance108.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance108.BackColor2 = System.Drawing.SystemColors.Control;
            appearance108.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance108.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboYesNo.DisplayLayout.GroupByBox.PromptAppearance = appearance108;
            this.cboYesNo.DisplayLayout.MaxColScrollRegions = 1;
            this.cboYesNo.DisplayLayout.MaxRowScrollRegions = 1;
            appearance109.BackColor = System.Drawing.SystemColors.Window;
            appearance109.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboYesNo.DisplayLayout.Override.ActiveCellAppearance = appearance109;
            appearance110.BackColor = System.Drawing.SystemColors.Highlight;
            appearance110.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboYesNo.DisplayLayout.Override.ActiveRowAppearance = appearance110;
            appearance111.FontData.BoldAsString = "True";
            this.cboYesNo.DisplayLayout.Override.ActiveRowCellAppearance = appearance111;
            this.cboYesNo.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboYesNo.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboYesNo.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance112.BackColor = System.Drawing.SystemColors.Window;
            this.cboYesNo.DisplayLayout.Override.CardAreaAppearance = appearance112;
            appearance113.BorderColor = System.Drawing.Color.Silver;
            appearance113.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboYesNo.DisplayLayout.Override.CellAppearance = appearance113;
            this.cboYesNo.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboYesNo.DisplayLayout.Override.CellPadding = 0;
            appearance114.BackColor = System.Drawing.SystemColors.Control;
            appearance114.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance114.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance114.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance114.BorderColor = System.Drawing.SystemColors.Window;
            this.cboYesNo.DisplayLayout.Override.GroupByRowAppearance = appearance114;
            appearance115.TextHAlignAsString = "Left";
            this.cboYesNo.DisplayLayout.Override.HeaderAppearance = appearance115;
            this.cboYesNo.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboYesNo.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance116.BackColor = System.Drawing.SystemColors.Window;
            appearance116.BorderColor = System.Drawing.Color.Silver;
            this.cboYesNo.DisplayLayout.Override.RowAppearance = appearance116;
            this.cboYesNo.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance117.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance117.FontData.BoldAsString = "True";
            this.cboYesNo.DisplayLayout.Override.SelectedRowAppearance = appearance117;
            appearance118.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboYesNo.DisplayLayout.Override.TemplateAddRowAppearance = appearance118;
            this.cboYesNo.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboYesNo.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboYesNo.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboYesNo.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboYesNo.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboYesNo.Location = new System.Drawing.Point(465, 335);
            this.cboYesNo.MajorCode = "YESNO";
            this.cboYesNo.Name = "cboYesNo";
            this.cboYesNo.ShowDefaultValue = false;
            this.cboYesNo.Size = new System.Drawing.Size(176, 25);
            this.cboYesNo.TabIndex = 14;
            // 
            // cboUSEFLAG
            // 
            this.cboUSEFLAG.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboUSEFLAG.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboUSEFLAG.DbConfig = null;
            this.cboUSEFLAG.DefaultValue = "";
            appearance91.BackColor = System.Drawing.SystemColors.Window;
            appearance91.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboUSEFLAG.DisplayLayout.Appearance = appearance91;
            this.cboUSEFLAG.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboUSEFLAG.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboUSEFLAG.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance92.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance92.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance92.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance92.BorderColor = System.Drawing.SystemColors.Window;
            this.cboUSEFLAG.DisplayLayout.GroupByBox.Appearance = appearance92;
            appearance93.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboUSEFLAG.DisplayLayout.GroupByBox.BandLabelAppearance = appearance93;
            this.cboUSEFLAG.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance94.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance94.BackColor2 = System.Drawing.SystemColors.Control;
            appearance94.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance94.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboUSEFLAG.DisplayLayout.GroupByBox.PromptAppearance = appearance94;
            this.cboUSEFLAG.DisplayLayout.MaxColScrollRegions = 1;
            this.cboUSEFLAG.DisplayLayout.MaxRowScrollRegions = 1;
            appearance95.BackColor = System.Drawing.SystemColors.Window;
            appearance95.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboUSEFLAG.DisplayLayout.Override.ActiveCellAppearance = appearance95;
            appearance96.BackColor = System.Drawing.SystemColors.Highlight;
            appearance96.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboUSEFLAG.DisplayLayout.Override.ActiveRowAppearance = appearance96;
            appearance97.FontData.BoldAsString = "True";
            this.cboUSEFLAG.DisplayLayout.Override.ActiveRowCellAppearance = appearance97;
            this.cboUSEFLAG.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboUSEFLAG.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboUSEFLAG.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance98.BackColor = System.Drawing.SystemColors.Window;
            this.cboUSEFLAG.DisplayLayout.Override.CardAreaAppearance = appearance98;
            appearance99.BorderColor = System.Drawing.Color.Silver;
            appearance99.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboUSEFLAG.DisplayLayout.Override.CellAppearance = appearance99;
            this.cboUSEFLAG.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboUSEFLAG.DisplayLayout.Override.CellPadding = 0;
            appearance100.BackColor = System.Drawing.SystemColors.Control;
            appearance100.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance100.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance100.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance100.BorderColor = System.Drawing.SystemColors.Window;
            this.cboUSEFLAG.DisplayLayout.Override.GroupByRowAppearance = appearance100;
            appearance101.TextHAlignAsString = "Left";
            this.cboUSEFLAG.DisplayLayout.Override.HeaderAppearance = appearance101;
            this.cboUSEFLAG.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboUSEFLAG.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance102.BackColor = System.Drawing.SystemColors.Window;
            appearance102.BorderColor = System.Drawing.Color.Silver;
            this.cboUSEFLAG.DisplayLayout.Override.RowAppearance = appearance102;
            this.cboUSEFLAG.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance103.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance103.FontData.BoldAsString = "True";
            this.cboUSEFLAG.DisplayLayout.Override.SelectedRowAppearance = appearance103;
            appearance104.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboUSEFLAG.DisplayLayout.Override.TemplateAddRowAppearance = appearance104;
            this.cboUSEFLAG.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboUSEFLAG.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboUSEFLAG.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboUSEFLAG.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboUSEFLAG.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboUSEFLAG.Location = new System.Drawing.Point(822, 248);
            this.cboUSEFLAG.MajorCode = "USEFLAG";
            this.cboUSEFLAG.Name = "cboUSEFLAG";
            this.cboUSEFLAG.ShowDefaultValue = false;
            this.cboUSEFLAG.Size = new System.Drawing.Size(239, 25);
            this.cboUSEFLAG.TabIndex = 13;
            this.cboUSEFLAG.Text = "sCodeNMComboBox4";
            // 
            // grid1
            // 
            this.grid1.ContextMenuCopyEnabled = true;
            this.grid1.ContextMenuDeleteEnabled = false;
            this.grid1.ContextMenuExcelEnabled = true;
            this.grid1.ContextMenuInsertEnabled = true;
            this.grid1.ContextMenuPasteEnabled = true;
            appearance51.BackColor = System.Drawing.SystemColors.Window;
            appearance51.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.grid1.DisplayLayout.Appearance = appearance51;
            this.grid1.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grid1.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.grid1.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.Empty;
            appearance52.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance52.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance52.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance52.BorderColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.GroupByBox.Appearance = appearance52;
            appearance53.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grid1.DisplayLayout.GroupByBox.BandLabelAppearance = appearance53;
            this.grid1.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grid1.DisplayLayout.GroupByBox.Hidden = true;
            appearance54.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance54.BackColor2 = System.Drawing.SystemColors.Control;
            appearance54.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance54.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grid1.DisplayLayout.GroupByBox.PromptAppearance = appearance54;
            this.grid1.DisplayLayout.MaxColScrollRegions = 1;
            this.grid1.DisplayLayout.MaxRowScrollRegions = 1;
            appearance55.BackColor = System.Drawing.SystemColors.Window;
            appearance55.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grid1.DisplayLayout.Override.ActiveCellAppearance = appearance55;
            appearance56.BackColor = System.Drawing.SystemColors.Highlight;
            appearance56.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.grid1.DisplayLayout.Override.ActiveRowAppearance = appearance56;
            this.grid1.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.True;
            this.grid1.DisplayLayout.Override.AllowMultiCellOperations = ((Infragistics.Win.UltraWinGrid.AllowMultiCellOperation)((((((((Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.CopyWithHeaders) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Cut) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Delete) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Paste) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Undo) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Redo) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Reserved)));
            this.grid1.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.grid1.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance57.BackColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.Override.CardAreaAppearance = appearance57;
            appearance58.BorderColor = System.Drawing.Color.Silver;
            appearance58.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.grid1.DisplayLayout.Override.CellAppearance = appearance58;
            this.grid1.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.grid1.DisplayLayout.Override.CellPadding = 0;
            appearance59.BackColor = System.Drawing.SystemColors.Control;
            appearance59.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance59.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance59.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance59.BorderColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.Override.GroupByRowAppearance = appearance59;
            appearance60.TextHAlignAsString = "Center";
            this.grid1.DisplayLayout.Override.HeaderAppearance = appearance60;
            this.grid1.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grid1.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance61.BackColor = System.Drawing.SystemColors.Window;
            appearance61.BorderColor = System.Drawing.Color.Silver;
            this.grid1.DisplayLayout.Override.RowAppearance = appearance61;
            this.grid1.DisplayLayout.Override.RowSelectorHeaderStyle = Infragistics.Win.UltraWinGrid.RowSelectorHeaderStyle.SeparateElement;
            this.grid1.DisplayLayout.Override.RowSelectorNumberStyle = Infragistics.Win.UltraWinGrid.RowSelectorNumberStyle.RowIndex;
            this.grid1.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.True;
            this.grid1.DisplayLayout.Override.RowSelectorStyle = Infragistics.Win.HeaderStyle.XPThemed;
            appearance62.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grid1.DisplayLayout.Override.TemplateAddRowAppearance = appearance62;
            this.grid1.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grid1.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grid1.DisplayLayout.SelectionOverlayBorderThickness = 2;
            this.grid1.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.grid1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grid1.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.grid1.Location = new System.Drawing.Point(6, 6);
            this.grid1.Name = "grid1";
            this.grid1.Size = new System.Drawing.Size(1124, 692);
            this.grid1.TabIndex = 0;
            this.grid1.Text = "grid1";
            this.grid1.TextRenderingMode = Infragistics.Win.TextRenderingMode.GDI;
            this.grid1.UpdateMode = Infragistics.Win.UltraWinGrid.UpdateMode.OnCellChange;
            this.grid1.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.grid1.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            // 
            // lblStopClass
            // 
            appearance48.TextHAlignAsString = "Right";
            appearance48.TextVAlignAsString = "Middle";
            this.lblStopClass.Appearance = appearance48;
            this.lblStopClass.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblStopClass.DbField = "cboUseFlag";
            this.lblStopClass.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblStopClass.Location = new System.Drawing.Point(390, 7);
            this.lblStopClass.Name = "lblStopClass";
            this.lblStopClass.Size = new System.Drawing.Size(103, 26);
            this.lblStopClass.TabIndex = 72;
            this.lblStopClass.Text = "비가동유형";
            // 
            // lblStopType
            // 
            appearance49.TextHAlignAsString = "Right";
            appearance49.TextVAlignAsString = "Middle";
            this.lblStopType.Appearance = appearance49;
            this.lblStopType.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblStopType.DbField = "cboUseFlag";
            this.lblStopType.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblStopType.Location = new System.Drawing.Point(390, 39);
            this.lblStopType.Name = "lblStopType";
            this.lblStopType.Size = new System.Drawing.Size(103, 26);
            this.lblStopType.TabIndex = 70;
            this.lblStopType.Text = "비가동구분";
            // 
            // lblUseFlag
            // 
            appearance50.TextHAlignAsString = "Right";
            appearance50.TextVAlignAsString = "Middle";
            this.lblUseFlag.Appearance = appearance50;
            this.lblUseFlag.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblUseFlag.DbField = "cboUseFlag";
            this.lblUseFlag.Font = new System.Drawing.Font("맑은 고딕", 9F);
            this.lblUseFlag.Location = new System.Drawing.Point(204, 6);
            this.lblUseFlag.Name = "lblUseFlag";
            this.lblUseFlag.Size = new System.Drawing.Size(67, 26);
            this.lblUseFlag.TabIndex = 69;
            this.lblUseFlag.Text = "사용여부";
            // 
            // txtPlantCode
            // 
            this.txtPlantCode.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtPlantCode.Location = new System.Drawing.Point(504, 176);
            this.txtPlantCode.Name = "txtPlantCode";
            this.txtPlantCode.ReadOnly = true;
            this.txtPlantCode.Size = new System.Drawing.Size(152, 25);
            this.txtPlantCode.TabIndex = 74;
            this.txtPlantCode.Visible = false;
            // 
            // lblPlantCode
            // 
            appearance119.TextHAlignAsString = "Right";
            appearance119.TextVAlignAsString = "Middle";
            this.lblPlantCode.Appearance = appearance119;
            this.lblPlantCode.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblPlantCode.DbField = null;
            this.lblPlantCode.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblPlantCode.Location = new System.Drawing.Point(438, 176);
            this.lblPlantCode.Name = "lblPlantCode";
            this.lblPlantCode.Size = new System.Drawing.Size(58, 25);
            this.lblPlantCode.TabIndex = 73;
            this.lblPlantCode.Text = "사업장";
            this.lblPlantCode.Visible = false;
            // 
            // txtOPCode
            // 
            this.txtOPCode.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtOPCode.Location = new System.Drawing.Point(716, 30);
            this.txtOPCode.Name = "txtOPCode";
            this.txtOPCode.Size = new System.Drawing.Size(116, 25);
            this.txtOPCode.TabIndex = 1;
            this.txtOPCode.Visible = false;
            // 
            // lblWorkCenterCode_H
            // 
            appearance47.TextHAlignAsString = "Right";
            appearance47.TextVAlignAsString = "Middle";
            this.lblWorkCenterCode_H.Appearance = appearance47;
            this.lblWorkCenterCode_H.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblWorkCenterCode_H.DbField = "cboUseFlag";
            this.lblWorkCenterCode_H.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblWorkCenterCode_H.Location = new System.Drawing.Point(660, 30);
            this.lblWorkCenterCode_H.Name = "lblWorkCenterCode_H";
            this.lblWorkCenterCode_H.Size = new System.Drawing.Size(50, 26);
            this.lblWorkCenterCode_H.TabIndex = 182;
            this.lblWorkCenterCode_H.Text = "공정";
            this.lblWorkCenterCode_H.Visible = false;
            // 
            // txtStopCode
            // 
            this.txtStopCode.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtStopCode.Location = new System.Drawing.Point(72, 40);
            this.txtStopCode.Name = "txtStopCode";
            this.txtStopCode.Size = new System.Drawing.Size(116, 25);
            this.txtStopCode.TabIndex = 3;
            // 
            // sLabel1
            // 
            appearance46.TextHAlignAsString = "Right";
            appearance46.TextVAlignAsString = "Middle";
            this.sLabel1.Appearance = appearance46;
            this.sLabel1.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.sLabel1.DbField = "cboUseFlag";
            this.sLabel1.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.sLabel1.Location = new System.Drawing.Point(16, 40);
            this.sLabel1.Name = "sLabel1";
            this.sLabel1.Size = new System.Drawing.Size(50, 26);
            this.sLabel1.TabIndex = 185;
            this.sLabel1.Text = "비가동";
            // 
            // cboUseFlag_H
            // 
            appearance31.FontData.Name = "맑은 고딕";
            appearance31.FontData.SizeInPoints = 9F;
            this.cboUseFlag_H.Appearance = appearance31;
            this.cboUseFlag_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboUseFlag_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboUseFlag_H.DbConfig = null;
            this.cboUseFlag_H.DefaultValue = "ALL";
            appearance32.BackColor = System.Drawing.SystemColors.Window;
            appearance32.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboUseFlag_H.DisplayLayout.Appearance = appearance32;
            this.cboUseFlag_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboUseFlag_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboUseFlag_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance33.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance33.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance33.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance33.BorderColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag_H.DisplayLayout.GroupByBox.Appearance = appearance33;
            appearance34.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboUseFlag_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance34;
            this.cboUseFlag_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance133.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance133.BackColor2 = System.Drawing.SystemColors.Control;
            appearance133.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance133.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboUseFlag_H.DisplayLayout.GroupByBox.PromptAppearance = appearance133;
            this.cboUseFlag_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboUseFlag_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance134.BackColor = System.Drawing.SystemColors.Window;
            appearance134.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboUseFlag_H.DisplayLayout.Override.ActiveCellAppearance = appearance134;
            appearance135.BackColor = System.Drawing.SystemColors.Highlight;
            appearance135.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboUseFlag_H.DisplayLayout.Override.ActiveRowAppearance = appearance135;
            appearance38.FontData.BoldAsString = "True";
            this.cboUseFlag_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance38;
            this.cboUseFlag_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboUseFlag_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboUseFlag_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance39.BackColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag_H.DisplayLayout.Override.CardAreaAppearance = appearance39;
            appearance40.BorderColor = System.Drawing.Color.Silver;
            appearance40.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboUseFlag_H.DisplayLayout.Override.CellAppearance = appearance40;
            this.cboUseFlag_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboUseFlag_H.DisplayLayout.Override.CellPadding = 0;
            appearance41.BackColor = System.Drawing.SystemColors.Control;
            appearance41.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance41.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance41.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance41.BorderColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag_H.DisplayLayout.Override.GroupByRowAppearance = appearance41;
            appearance42.TextHAlignAsString = "Left";
            this.cboUseFlag_H.DisplayLayout.Override.HeaderAppearance = appearance42;
            this.cboUseFlag_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboUseFlag_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance43.BackColor = System.Drawing.SystemColors.Window;
            appearance43.BorderColor = System.Drawing.Color.Silver;
            this.cboUseFlag_H.DisplayLayout.Override.RowAppearance = appearance43;
            this.cboUseFlag_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance44.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance44.FontData.BoldAsString = "True";
            this.cboUseFlag_H.DisplayLayout.Override.SelectedRowAppearance = appearance44;
            appearance45.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboUseFlag_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance45;
            this.cboUseFlag_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboUseFlag_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboUseFlag_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboUseFlag_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboUseFlag_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboUseFlag_H.Location = new System.Drawing.Point(277, 7);
            this.cboUseFlag_H.MajorCode = "USEFLAG";
            this.cboUseFlag_H.Name = "cboUseFlag_H";
            this.cboUseFlag_H.ShowDefaultValue = false;
            this.cboUseFlag_H.Size = new System.Drawing.Size(116, 24);
            this.cboUseFlag_H.TabIndex = 7;
            this.cboUseFlag_H.Text = "ALL";
            // 
            // cboStopClass_H
            // 
            appearance131.FontData.Name = "맑은 고딕";
            appearance131.FontData.SizeInPoints = 9F;
            this.cboStopClass_H.Appearance = appearance131;
            this.cboStopClass_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboStopClass_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboStopClass_H.DbConfig = null;
            this.cboStopClass_H.DefaultValue = "ALL";
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboStopClass_H.DisplayLayout.Appearance = appearance17;
            this.cboStopClass_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboStopClass_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboStopClass_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance18.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance18.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance18.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance18.BorderColor = System.Drawing.SystemColors.Window;
            this.cboStopClass_H.DisplayLayout.GroupByBox.Appearance = appearance18;
            appearance19.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboStopClass_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance19;
            this.cboStopClass_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance20.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance20.BackColor2 = System.Drawing.SystemColors.Control;
            appearance20.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance20.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboStopClass_H.DisplayLayout.GroupByBox.PromptAppearance = appearance20;
            this.cboStopClass_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboStopClass_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance21.BackColor = System.Drawing.SystemColors.Window;
            appearance21.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboStopClass_H.DisplayLayout.Override.ActiveCellAppearance = appearance21;
            appearance132.BackColor = System.Drawing.SystemColors.Highlight;
            appearance132.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboStopClass_H.DisplayLayout.Override.ActiveRowAppearance = appearance132;
            appearance23.FontData.BoldAsString = "True";
            this.cboStopClass_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance23;
            this.cboStopClass_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboStopClass_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboStopClass_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance24.BackColor = System.Drawing.SystemColors.Window;
            this.cboStopClass_H.DisplayLayout.Override.CardAreaAppearance = appearance24;
            appearance25.BorderColor = System.Drawing.Color.Silver;
            appearance25.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboStopClass_H.DisplayLayout.Override.CellAppearance = appearance25;
            this.cboStopClass_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboStopClass_H.DisplayLayout.Override.CellPadding = 0;
            appearance26.BackColor = System.Drawing.SystemColors.Control;
            appearance26.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance26.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance26.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance26.BorderColor = System.Drawing.SystemColors.Window;
            this.cboStopClass_H.DisplayLayout.Override.GroupByRowAppearance = appearance26;
            appearance27.TextHAlignAsString = "Left";
            this.cboStopClass_H.DisplayLayout.Override.HeaderAppearance = appearance27;
            this.cboStopClass_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboStopClass_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance28.BackColor = System.Drawing.SystemColors.Window;
            appearance28.BorderColor = System.Drawing.Color.Silver;
            this.cboStopClass_H.DisplayLayout.Override.RowAppearance = appearance28;
            this.cboStopClass_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance29.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance29.FontData.BoldAsString = "True";
            this.cboStopClass_H.DisplayLayout.Override.SelectedRowAppearance = appearance29;
            appearance30.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboStopClass_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance30;
            this.cboStopClass_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboStopClass_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboStopClass_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboStopClass_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboStopClass_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboStopClass_H.Location = new System.Drawing.Point(499, 8);
            this.cboStopClass_H.MajorCode = "STOPCLASS";
            this.cboStopClass_H.Name = "cboStopClass_H";
            this.cboStopClass_H.ShowDefaultValue = false;
            this.cboStopClass_H.Size = new System.Drawing.Size(154, 24);
            this.cboStopClass_H.TabIndex = 5;
            this.cboStopClass_H.Text = "ALL";
            // 
            // cboStopType_H
            // 
            appearance1.FontData.Name = "맑은 고딕";
            appearance1.FontData.SizeInPoints = 9F;
            this.cboStopType_H.Appearance = appearance1;
            this.cboStopType_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboStopType_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboStopType_H.DbConfig = null;
            this.cboStopType_H.DefaultValue = "ALL";
            appearance120.BackColor = System.Drawing.SystemColors.Window;
            appearance120.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboStopType_H.DisplayLayout.Appearance = appearance120;
            this.cboStopType_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboStopType_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboStopType_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance3.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance3.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance3.BorderColor = System.Drawing.SystemColors.Window;
            this.cboStopType_H.DisplayLayout.GroupByBox.Appearance = appearance3;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboStopType_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance4;
            this.cboStopType_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance5.BackColor2 = System.Drawing.SystemColors.Control;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboStopType_H.DisplayLayout.GroupByBox.PromptAppearance = appearance5;
            this.cboStopType_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboStopType_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance121.BackColor = System.Drawing.SystemColors.Window;
            appearance121.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboStopType_H.DisplayLayout.Override.ActiveCellAppearance = appearance121;
            appearance122.BackColor = System.Drawing.SystemColors.Highlight;
            appearance122.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboStopType_H.DisplayLayout.Override.ActiveRowAppearance = appearance122;
            appearance123.FontData.BoldAsString = "True";
            this.cboStopType_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance123;
            this.cboStopType_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboStopType_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboStopType_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance124.BackColor = System.Drawing.SystemColors.Window;
            this.cboStopType_H.DisplayLayout.Override.CardAreaAppearance = appearance124;
            appearance125.BorderColor = System.Drawing.Color.Silver;
            appearance125.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboStopType_H.DisplayLayout.Override.CellAppearance = appearance125;
            this.cboStopType_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboStopType_H.DisplayLayout.Override.CellPadding = 0;
            appearance126.BackColor = System.Drawing.SystemColors.Control;
            appearance126.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance126.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance126.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance126.BorderColor = System.Drawing.SystemColors.Window;
            this.cboStopType_H.DisplayLayout.Override.GroupByRowAppearance = appearance126;
            appearance127.TextHAlignAsString = "Left";
            this.cboStopType_H.DisplayLayout.Override.HeaderAppearance = appearance127;
            this.cboStopType_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboStopType_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance128.BackColor = System.Drawing.SystemColors.Window;
            appearance128.BorderColor = System.Drawing.Color.Silver;
            this.cboStopType_H.DisplayLayout.Override.RowAppearance = appearance128;
            this.cboStopType_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance129.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance129.FontData.BoldAsString = "True";
            this.cboStopType_H.DisplayLayout.Override.SelectedRowAppearance = appearance129;
            appearance130.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboStopType_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance130;
            this.cboStopType_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboStopType_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboStopType_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboStopType_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboStopType_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboStopType_H.Location = new System.Drawing.Point(499, 40);
            this.cboStopType_H.MajorCode = "STOPTYPE";
            this.cboStopType_H.Name = "cboStopType_H";
            this.cboStopType_H.ShowDefaultValue = false;
            this.cboStopType_H.Size = new System.Drawing.Size(154, 24);
            this.cboStopType_H.TabIndex = 6;
            this.cboStopType_H.Text = "ALL";
            // 
            // txtStopName
            // 
            this.txtStopName.BackColor = System.Drawing.SystemColors.InactiveBorder;
            this.txtStopName.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtStopName.Location = new System.Drawing.Point(194, 40);
            this.txtStopName.Name = "txtStopName";
            this.txtStopName.Size = new System.Drawing.Size(199, 25);
            this.txtStopName.TabIndex = 4;
            // 
            // txtOPName
            // 
            this.txtOPName.BackColor = System.Drawing.SystemColors.InactiveBorder;
            this.txtOPName.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtOPName.Location = new System.Drawing.Point(838, 30);
            this.txtOPName.Name = "txtOPName";
            this.txtOPName.Size = new System.Drawing.Size(199, 25);
            this.txtOPName.TabIndex = 2;
            this.txtOPName.Visible = false;
            // 
            // cboPlantCode_H
            // 
            appearance2.FontData.Name = "맑은 고딕";
            appearance2.FontData.SizeInPoints = 9F;
            this.cboPlantCode_H.Appearance = appearance2;
            this.cboPlantCode_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboPlantCode_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboPlantCode_H.DbConfig = null;
            this.cboPlantCode_H.DefaultValue = "ALL";
            appearance35.BackColor = System.Drawing.SystemColors.Window;
            appearance35.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboPlantCode_H.DisplayLayout.Appearance = appearance35;
            this.cboPlantCode_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboPlantCode_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboPlantCode_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance36.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance36.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance36.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance36.BorderColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.Appearance = appearance36;
            appearance37.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance37;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance6.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance6.BackColor2 = System.Drawing.SystemColors.Control;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.PromptAppearance = appearance6;
            this.cboPlantCode_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboPlantCode_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            appearance7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboPlantCode_H.DisplayLayout.Override.ActiveCellAppearance = appearance7;
            appearance8.BackColor = System.Drawing.SystemColors.Highlight;
            appearance8.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboPlantCode_H.DisplayLayout.Override.ActiveRowAppearance = appearance8;
            appearance9.FontData.BoldAsString = "True";
            this.cboPlantCode_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance9;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.Override.CardAreaAppearance = appearance10;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            appearance11.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboPlantCode_H.DisplayLayout.Override.CellAppearance = appearance11;
            this.cboPlantCode_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboPlantCode_H.DisplayLayout.Override.CellPadding = 0;
            appearance12.BackColor = System.Drawing.SystemColors.Control;
            appearance12.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance12.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance12.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance12.BorderColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.Override.GroupByRowAppearance = appearance12;
            appearance13.TextHAlignAsString = "Left";
            this.cboPlantCode_H.DisplayLayout.Override.HeaderAppearance = appearance13;
            this.cboPlantCode_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboPlantCode_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            this.cboPlantCode_H.DisplayLayout.Override.RowAppearance = appearance14;
            this.cboPlantCode_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance15.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance15.FontData.BoldAsString = "True";
            this.cboPlantCode_H.DisplayLayout.Override.SelectedRowAppearance = appearance15;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboPlantCode_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance16;
            this.cboPlantCode_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboPlantCode_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboPlantCode_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboPlantCode_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboPlantCode_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboPlantCode_H.Location = new System.Drawing.Point(72, 8);
            this.cboPlantCode_H.MajorCode = "PLANTCODE";
            this.cboPlantCode_H.Name = "cboPlantCode_H";
            this.cboPlantCode_H.ShowDefaultValue = false;
            this.cboPlantCode_H.Size = new System.Drawing.Size(116, 24);
            this.cboPlantCode_H.TabIndex = 551;
            this.cboPlantCode_H.Text = "ALL";
            // 
            // sLabel5
            // 
            appearance22.TextHAlignAsString = "Right";
            appearance22.TextVAlignAsString = "Middle";
            this.sLabel5.Appearance = appearance22;
            this.sLabel5.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.sLabel5.DbField = "cboUseFlag";
            this.sLabel5.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.sLabel5.Location = new System.Drawing.Point(14, 7);
            this.sLabel5.Name = "sLabel5";
            this.sLabel5.Size = new System.Drawing.Size(52, 26);
            this.sLabel5.TabIndex = 550;
            this.sLabel5.Text = "사업장";
            // 
            // BM1100
            // 
            this.ClientSize = new System.Drawing.Size(1136, 778);
            this.Name = "BM1100";
            this.Load += new System.EventHandler(this.BM1100_Load);
            ((System.ComponentModel.ISupportInitialize)(this.gbxHeader)).EndInit();
            this.gbxHeader.ResumeLayout(false);
            this.gbxHeader.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gbxBody)).EndInit();
            this.gbxBody.ResumeLayout(false);
            this.gbxBody.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cboStopType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboSTOPCLASS)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboYesNo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboUSEFLAG)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grid1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboUseFlag_H)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboStopClass_H)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboStopType_H)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboPlantCode_H)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Control.Grid grid1;
        private Control.SCodeNMComboBox cboStopType;
        private Control.SCodeNMComboBox cboSTOPCLASS;
        private Control.SCodeNMComboBox cboUSEFLAG;
        private Control.SCodeNMComboBox cboYesNo;
        private Control.SLabel lblStopClass;
        private Control.SLabel lblStopType;
        private Control.SLabel lblUseFlag;
        private System.Windows.Forms.TextBox txtPlantCode;
        private Control.SLabel lblPlantCode;
        private System.Windows.Forms.TextBox txtOPCode;
        private Control.SLabel lblWorkCenterCode_H;
        private System.Windows.Forms.TextBox txtStopCode;
        private Control.SLabel sLabel1;
        private Control.SCodeNMComboBox cboStopType_H;
        private Control.SCodeNMComboBox cboStopClass_H;
        private Control.SCodeNMComboBox cboUseFlag_H;
        private System.Windows.Forms.TextBox txtStopName;
        private System.Windows.Forms.TextBox txtOPName;
        private Control.SCodeNMComboBox cboPlantCode_H;
        private Control.SLabel sLabel5;
    }
}
