namespace SAMMI.BM
{
    partial class BM5100
    {
        /// <summary>
        /// 필수 디자이너 변수입니다.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 사용 중인 모든 리소스를 정리합니다.
        /// </summary>
        /// <param name="disposing">관리되는 리소스를 삭제해야 하면 true이고, 그렇지 않으면 false입니다.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form 디자이너에서 생성한 코드

        /// <summary>
        /// 디자이너 지원에 필요한 메서드입니다.
        /// 이 메서드의 내용을 코드 편집기로 수정하지 마십시오.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance65 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance66 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance67 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance68 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance69 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance70 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance71 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance72 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance73 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance74 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance75 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(BM5100));
            Infragistics.Win.Appearance appearance76 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand2 = new Infragistics.Win.UltraWinGrid.UltraGridBand("dTable1", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn1 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("UnitCode");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn2 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("UnitName");
            Infragistics.Win.Appearance appearance77 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance78 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance79 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance80 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance81 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance82 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance83 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance84 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance85 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance86 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance87 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance88 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance89 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance90 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance91 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance92 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance93 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance94 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance95 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance96 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance97 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance98 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance99 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance100 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance101 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance102 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance103 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance104 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance105 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance106 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance107 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance108 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance109 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance110 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance111 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance112 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance113 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance114 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance115 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance116 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance117 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance118 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance119 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance120 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance121 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance122 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance123 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance124 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance125 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance126 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance127 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance128 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance129 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance130 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance131 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand3 = new Infragistics.Win.UltraWinGrid.UltraGridBand("dTable1", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn3 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("WHCode");
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn4 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("WHName");
            Infragistics.Win.Appearance appearance132 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance133 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance134 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance148 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand1 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.Appearance appearance149 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance150 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance135 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance136 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance137 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance138 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance139 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance140 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance141 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance142 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance143 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance144 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance145 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance146 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance147 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            this.lblUseFlag = new SAMMI.Control.SLabel();
            this.lblItemType = new SAMMI.Control.SLabel();
            this.lblItemCode = new SAMMI.Control.SLabel();
            this.txtItemCode = new System.Windows.Forms.TextBox();
            this.cboUseFlag = new SAMMI.Control.SCodeNMComboBox();
            this.cboCarType = new SAMMI.Control.SCodeNMComboBox();
            this.cbotUnitCode = new SAMMI.Control.ScboGetUnitCode();
            this.cboYesNo = new SAMMI.Control.SCodeNMComboBox();
            this.cboITEMGROUP = new SAMMI.Control.SCodeNMComboBox();
            this.cboITEMSPEC = new SAMMI.Control.SCodeNMComboBox();
            this.cboWHCode = new SAMMI.Control.ScboGetWHCode();
            this.grid1 = new SAMMI.Control.Grid(this.components);
            this.lblPlantCode = new SAMMI.Control.SLabel();
            this.txtPlantCode = new System.Windows.Forms.TextBox();
            this.cboUseFlag_H = new SAMMI.Control.SCodeNMComboBox();
            this.cboItemType_H = new SAMMI.Control.SCodeNMComboBox();
            this.txtItemName = new System.Windows.Forms.TextBox();
            this.cboPlantCode_H = new SAMMI.Control.SCodeNMComboBox();
            this.sLabel5 = new SAMMI.Control.SLabel();
            ((System.ComponentModel.ISupportInitialize)(this.gbxHeader)).BeginInit();
            this.gbxHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gbxBody)).BeginInit();
            this.gbxBody.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cboUseFlag)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboCarType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbotUnitCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboYesNo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboITEMGROUP)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboITEMSPEC)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboWHCode)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grid1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboUseFlag_H)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboItemType_H)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboPlantCode_H)).BeginInit();
            this.SuspendLayout();
            // 
            // gbxHeader
            // 
            this.gbxHeader.ContentPadding.Bottom = 2;
            this.gbxHeader.ContentPadding.Left = 2;
            this.gbxHeader.ContentPadding.Right = 2;
            this.gbxHeader.ContentPadding.Top = 4;
            this.gbxHeader.Controls.Add(this.cboPlantCode_H);
            this.gbxHeader.Controls.Add(this.sLabel5);
            this.gbxHeader.Controls.Add(this.txtItemName);
            this.gbxHeader.Controls.Add(this.cboItemType_H);
            this.gbxHeader.Controls.Add(this.cboUseFlag_H);
            this.gbxHeader.Controls.Add(this.txtPlantCode);
            this.gbxHeader.Controls.Add(this.txtItemCode);
            this.gbxHeader.Controls.Add(this.lblItemCode);
            this.gbxHeader.Controls.Add(this.lblItemType);
            this.gbxHeader.Controls.Add(this.lblUseFlag);
            this.gbxHeader.Controls.Add(this.lblPlantCode);
            this.gbxHeader.Size = new System.Drawing.Size(1028, 71);
            // 
            // gbxBody
            // 
            this.gbxBody.ContentPadding.Bottom = 4;
            this.gbxBody.ContentPadding.Left = 4;
            this.gbxBody.ContentPadding.Right = 4;
            this.gbxBody.ContentPadding.Top = 6;
            this.gbxBody.Controls.Add(this.grid1);
            this.gbxBody.Controls.Add(this.cboUseFlag);
            this.gbxBody.Controls.Add(this.cboCarType);
            this.gbxBody.Controls.Add(this.cbotUnitCode);
            this.gbxBody.Controls.Add(this.cboYesNo);
            this.gbxBody.Controls.Add(this.cboITEMGROUP);
            this.gbxBody.Controls.Add(this.cboITEMSPEC);
            this.gbxBody.Controls.Add(this.cboWHCode);
            this.gbxBody.Location = new System.Drawing.Point(0, 71);
            this.gbxBody.Size = new System.Drawing.Size(1028, 675);
            // 
            // lblUseFlag
            // 
            appearance33.TextHAlignAsString = "Right";
            appearance33.TextVAlignAsString = "Middle";
            this.lblUseFlag.Appearance = appearance33;
            this.lblUseFlag.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblUseFlag.DbField = null;
            this.lblUseFlag.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblUseFlag.Location = new System.Drawing.Point(195, 6);
            this.lblUseFlag.Name = "lblUseFlag";
            this.lblUseFlag.Size = new System.Drawing.Size(71, 25);
            this.lblUseFlag.TabIndex = 20;
            this.lblUseFlag.Text = "사용여부";
            // 
            // lblItemType
            // 
            appearance32.TextHAlignAsString = "Right";
            appearance32.TextVAlignAsString = "Middle";
            this.lblItemType.Appearance = appearance32;
            this.lblItemType.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblItemType.DbField = null;
            this.lblItemType.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblItemType.Location = new System.Drawing.Point(402, 6);
            this.lblItemType.Name = "lblItemType";
            this.lblItemType.Size = new System.Drawing.Size(71, 25);
            this.lblItemType.TabIndex = 21;
            this.lblItemType.Text = "제품유형";
            // 
            // lblItemCode
            // 
            appearance31.TextHAlignAsString = "Right";
            appearance31.TextVAlignAsString = "Middle";
            this.lblItemCode.Appearance = appearance31;
            this.lblItemCode.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblItemCode.DbField = null;
            this.lblItemCode.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblItemCode.Location = new System.Drawing.Point(3, 36);
            this.lblItemCode.Name = "lblItemCode";
            this.lblItemCode.Size = new System.Drawing.Size(61, 25);
            this.lblItemCode.TabIndex = 22;
            this.lblItemCode.Text = "품  목";
            // 
            // txtItemCode
            // 
            this.txtItemCode.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtItemCode.Location = new System.Drawing.Point(70, 36);
            this.txtItemCode.Name = "txtItemCode";
            this.txtItemCode.Size = new System.Drawing.Size(119, 25);
            this.txtItemCode.TabIndex = 1;
            // 
            // cboUseFlag
            // 
            this.cboUseFlag.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboUseFlag.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboUseFlag.DbConfig = null;
            this.cboUseFlag.DefaultValue = "";
            appearance48.BackColor = System.Drawing.SystemColors.Window;
            appearance48.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboUseFlag.DisplayLayout.Appearance = appearance48;
            this.cboUseFlag.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboUseFlag.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboUseFlag.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance49.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance49.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance49.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance49.BorderColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag.DisplayLayout.GroupByBox.Appearance = appearance49;
            appearance50.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboUseFlag.DisplayLayout.GroupByBox.BandLabelAppearance = appearance50;
            this.cboUseFlag.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance51.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance51.BackColor2 = System.Drawing.SystemColors.Control;
            appearance51.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance51.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboUseFlag.DisplayLayout.GroupByBox.PromptAppearance = appearance51;
            this.cboUseFlag.DisplayLayout.MaxColScrollRegions = 1;
            this.cboUseFlag.DisplayLayout.MaxRowScrollRegions = 1;
            appearance52.BackColor = System.Drawing.SystemColors.Window;
            appearance52.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboUseFlag.DisplayLayout.Override.ActiveCellAppearance = appearance52;
            appearance53.BackColor = System.Drawing.SystemColors.Highlight;
            appearance53.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboUseFlag.DisplayLayout.Override.ActiveRowAppearance = appearance53;
            appearance54.FontData.BoldAsString = "True";
            this.cboUseFlag.DisplayLayout.Override.ActiveRowCellAppearance = appearance54;
            this.cboUseFlag.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboUseFlag.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboUseFlag.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance55.BackColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag.DisplayLayout.Override.CardAreaAppearance = appearance55;
            appearance56.BorderColor = System.Drawing.Color.Silver;
            appearance56.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboUseFlag.DisplayLayout.Override.CellAppearance = appearance56;
            this.cboUseFlag.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboUseFlag.DisplayLayout.Override.CellPadding = 0;
            appearance57.BackColor = System.Drawing.SystemColors.Control;
            appearance57.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance57.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance57.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance57.BorderColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag.DisplayLayout.Override.GroupByRowAppearance = appearance57;
            appearance58.TextHAlignAsString = "Left";
            this.cboUseFlag.DisplayLayout.Override.HeaderAppearance = appearance58;
            this.cboUseFlag.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboUseFlag.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance59.BackColor = System.Drawing.SystemColors.Window;
            appearance59.BorderColor = System.Drawing.Color.Silver;
            this.cboUseFlag.DisplayLayout.Override.RowAppearance = appearance59;
            this.cboUseFlag.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance60.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance60.FontData.BoldAsString = "True";
            this.cboUseFlag.DisplayLayout.Override.SelectedRowAppearance = appearance60;
            appearance61.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboUseFlag.DisplayLayout.Override.TemplateAddRowAppearance = appearance61;
            this.cboUseFlag.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboUseFlag.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboUseFlag.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboUseFlag.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboUseFlag.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboUseFlag.Location = new System.Drawing.Point(492, 172);
            this.cboUseFlag.MajorCode = "UseFlag";
            this.cboUseFlag.Name = "cboUseFlag";
            this.cboUseFlag.ShowDefaultValue = false;
            this.cboUseFlag.Size = new System.Drawing.Size(154, 25);
            this.cboUseFlag.TabIndex = 32;
            // 
            // cboCarType
            // 
            this.cboCarType.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboCarType.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboCarType.DbConfig = null;
            this.cboCarType.DefaultValue = "";
            appearance62.BackColor = System.Drawing.SystemColors.Window;
            appearance62.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboCarType.DisplayLayout.Appearance = appearance62;
            this.cboCarType.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboCarType.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboCarType.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance63.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance63.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance63.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance63.BorderColor = System.Drawing.SystemColors.Window;
            this.cboCarType.DisplayLayout.GroupByBox.Appearance = appearance63;
            appearance64.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboCarType.DisplayLayout.GroupByBox.BandLabelAppearance = appearance64;
            this.cboCarType.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance65.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance65.BackColor2 = System.Drawing.SystemColors.Control;
            appearance65.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance65.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboCarType.DisplayLayout.GroupByBox.PromptAppearance = appearance65;
            this.cboCarType.DisplayLayout.MaxColScrollRegions = 1;
            this.cboCarType.DisplayLayout.MaxRowScrollRegions = 1;
            appearance66.BackColor = System.Drawing.SystemColors.Window;
            appearance66.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboCarType.DisplayLayout.Override.ActiveCellAppearance = appearance66;
            appearance67.BackColor = System.Drawing.SystemColors.Highlight;
            appearance67.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboCarType.DisplayLayout.Override.ActiveRowAppearance = appearance67;
            appearance68.FontData.BoldAsString = "True";
            this.cboCarType.DisplayLayout.Override.ActiveRowCellAppearance = appearance68;
            this.cboCarType.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboCarType.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboCarType.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance69.BackColor = System.Drawing.SystemColors.Window;
            this.cboCarType.DisplayLayout.Override.CardAreaAppearance = appearance69;
            appearance70.BorderColor = System.Drawing.Color.Silver;
            appearance70.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboCarType.DisplayLayout.Override.CellAppearance = appearance70;
            this.cboCarType.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboCarType.DisplayLayout.Override.CellPadding = 0;
            appearance71.BackColor = System.Drawing.SystemColors.Control;
            appearance71.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance71.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance71.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance71.BorderColor = System.Drawing.SystemColors.Window;
            this.cboCarType.DisplayLayout.Override.GroupByRowAppearance = appearance71;
            appearance72.TextHAlignAsString = "Left";
            this.cboCarType.DisplayLayout.Override.HeaderAppearance = appearance72;
            this.cboCarType.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboCarType.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance73.BackColor = System.Drawing.SystemColors.Window;
            appearance73.BorderColor = System.Drawing.Color.Silver;
            this.cboCarType.DisplayLayout.Override.RowAppearance = appearance73;
            this.cboCarType.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance74.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance74.FontData.BoldAsString = "True";
            this.cboCarType.DisplayLayout.Override.SelectedRowAppearance = appearance74;
            appearance75.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboCarType.DisplayLayout.Override.TemplateAddRowAppearance = appearance75;
            this.cboCarType.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboCarType.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboCarType.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboCarType.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboCarType.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboCarType.Location = new System.Drawing.Point(332, 172);
            this.cboCarType.MajorCode = "CARTYPE";
            this.cboCarType.Name = "cboCarType";
            this.cboCarType.ShowDefaultValue = false;
            this.cboCarType.Size = new System.Drawing.Size(154, 25);
            this.cboCarType.TabIndex = 31;
            // 
            // cbotUnitCode
            // 
            this.cbotUnitCode.AutoSize = false;
            this.cbotUnitCode.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cbotUnitCode.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cbotUnitCode.DataMember = "dTable1";
            this.cbotUnitCode.DbConfig = null;
            this.cbotUnitCode.DefaultValue = "";
            appearance76.BackColor = System.Drawing.SystemColors.Window;
            appearance76.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cbotUnitCode.DisplayLayout.Appearance = appearance76;
            this.cbotUnitCode.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn1.Header.VisiblePosition = 0;
            ultraGridColumn2.Header.VisiblePosition = 1;
            ultraGridBand2.Columns.AddRange(new object[] {
            ultraGridColumn1,
            ultraGridColumn2});
            this.cbotUnitCode.DisplayLayout.BandsSerializer.Add(ultraGridBand2);
            this.cbotUnitCode.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cbotUnitCode.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance77.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance77.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance77.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance77.BorderColor = System.Drawing.SystemColors.Window;
            this.cbotUnitCode.DisplayLayout.GroupByBox.Appearance = appearance77;
            appearance78.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cbotUnitCode.DisplayLayout.GroupByBox.BandLabelAppearance = appearance78;
            this.cbotUnitCode.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance79.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance79.BackColor2 = System.Drawing.SystemColors.Control;
            appearance79.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance79.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cbotUnitCode.DisplayLayout.GroupByBox.PromptAppearance = appearance79;
            this.cbotUnitCode.DisplayLayout.MaxColScrollRegions = 1;
            this.cbotUnitCode.DisplayLayout.MaxRowScrollRegions = 1;
            appearance80.BackColor = System.Drawing.SystemColors.Window;
            appearance80.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cbotUnitCode.DisplayLayout.Override.ActiveCellAppearance = appearance80;
            appearance81.BackColor = System.Drawing.SystemColors.Highlight;
            appearance81.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cbotUnitCode.DisplayLayout.Override.ActiveRowAppearance = appearance81;
            appearance82.FontData.BoldAsString = "True";
            this.cbotUnitCode.DisplayLayout.Override.ActiveRowCellAppearance = appearance82;
            this.cbotUnitCode.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cbotUnitCode.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cbotUnitCode.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance83.BackColor = System.Drawing.SystemColors.Window;
            this.cbotUnitCode.DisplayLayout.Override.CardAreaAppearance = appearance83;
            appearance84.BorderColor = System.Drawing.Color.Silver;
            appearance84.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cbotUnitCode.DisplayLayout.Override.CellAppearance = appearance84;
            this.cbotUnitCode.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cbotUnitCode.DisplayLayout.Override.CellPadding = 0;
            appearance85.BackColor = System.Drawing.SystemColors.Control;
            appearance85.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance85.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance85.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance85.BorderColor = System.Drawing.SystemColors.Window;
            this.cbotUnitCode.DisplayLayout.Override.GroupByRowAppearance = appearance85;
            appearance86.TextHAlignAsString = "Left";
            this.cbotUnitCode.DisplayLayout.Override.HeaderAppearance = appearance86;
            this.cbotUnitCode.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cbotUnitCode.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance87.BackColor = System.Drawing.SystemColors.Window;
            appearance87.BorderColor = System.Drawing.Color.Silver;
            this.cbotUnitCode.DisplayLayout.Override.RowAppearance = appearance87;
            this.cbotUnitCode.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance88.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance88.FontData.BoldAsString = "True";
            this.cbotUnitCode.DisplayLayout.Override.SelectedRowAppearance = appearance88;
            appearance89.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cbotUnitCode.DisplayLayout.Override.TemplateAddRowAppearance = appearance89;
            this.cbotUnitCode.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cbotUnitCode.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cbotUnitCode.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cbotUnitCode.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cbotUnitCode.DisplayMember = "UnitName";
            this.cbotUnitCode.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cbotUnitCode.Location = new System.Drawing.Point(172, 169);
            this.cbotUnitCode.Name = "cbotUnitCode";
            this.cbotUnitCode.ShowDefaultValue = false;
            this.cbotUnitCode.Size = new System.Drawing.Size(154, 26);
            this.cbotUnitCode.TabIndex = 30;
            this.cbotUnitCode.Text = "scboGetUnitCode1";
            this.cbotUnitCode.UnitType = null;
            this.cbotUnitCode.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.cbotUnitCode.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.cbotUnitCode.ValueMember = "UnitCode";
            // 
            // cboYesNo
            // 
            this.cboYesNo.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboYesNo.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboYesNo.DbConfig = null;
            this.cboYesNo.DefaultValue = "";
            appearance90.BackColor = System.Drawing.SystemColors.Window;
            appearance90.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboYesNo.DisplayLayout.Appearance = appearance90;
            this.cboYesNo.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboYesNo.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboYesNo.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance91.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance91.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance91.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance91.BorderColor = System.Drawing.SystemColors.Window;
            this.cboYesNo.DisplayLayout.GroupByBox.Appearance = appearance91;
            appearance92.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboYesNo.DisplayLayout.GroupByBox.BandLabelAppearance = appearance92;
            this.cboYesNo.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance93.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance93.BackColor2 = System.Drawing.SystemColors.Control;
            appearance93.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance93.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboYesNo.DisplayLayout.GroupByBox.PromptAppearance = appearance93;
            this.cboYesNo.DisplayLayout.MaxColScrollRegions = 1;
            this.cboYesNo.DisplayLayout.MaxRowScrollRegions = 1;
            appearance94.BackColor = System.Drawing.SystemColors.Window;
            appearance94.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboYesNo.DisplayLayout.Override.ActiveCellAppearance = appearance94;
            appearance95.BackColor = System.Drawing.SystemColors.Highlight;
            appearance95.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboYesNo.DisplayLayout.Override.ActiveRowAppearance = appearance95;
            appearance96.FontData.BoldAsString = "True";
            this.cboYesNo.DisplayLayout.Override.ActiveRowCellAppearance = appearance96;
            this.cboYesNo.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboYesNo.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboYesNo.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance97.BackColor = System.Drawing.SystemColors.Window;
            this.cboYesNo.DisplayLayout.Override.CardAreaAppearance = appearance97;
            appearance98.BorderColor = System.Drawing.Color.Silver;
            appearance98.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboYesNo.DisplayLayout.Override.CellAppearance = appearance98;
            this.cboYesNo.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboYesNo.DisplayLayout.Override.CellPadding = 0;
            appearance99.BackColor = System.Drawing.SystemColors.Control;
            appearance99.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance99.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance99.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance99.BorderColor = System.Drawing.SystemColors.Window;
            this.cboYesNo.DisplayLayout.Override.GroupByRowAppearance = appearance99;
            appearance100.TextHAlignAsString = "Left";
            this.cboYesNo.DisplayLayout.Override.HeaderAppearance = appearance100;
            this.cboYesNo.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboYesNo.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance101.BackColor = System.Drawing.SystemColors.Window;
            appearance101.BorderColor = System.Drawing.Color.Silver;
            this.cboYesNo.DisplayLayout.Override.RowAppearance = appearance101;
            this.cboYesNo.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance102.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance102.FontData.BoldAsString = "True";
            this.cboYesNo.DisplayLayout.Override.SelectedRowAppearance = appearance102;
            appearance103.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboYesNo.DisplayLayout.Override.TemplateAddRowAppearance = appearance103;
            this.cboYesNo.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboYesNo.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboYesNo.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboYesNo.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboYesNo.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboYesNo.Location = new System.Drawing.Point(12, 169);
            this.cboYesNo.MajorCode = "YesNo";
            this.cboYesNo.Name = "cboYesNo";
            this.cboYesNo.ShowDefaultValue = false;
            this.cboYesNo.Size = new System.Drawing.Size(154, 25);
            this.cboYesNo.TabIndex = 28;
            // 
            // cboITEMGROUP
            // 
            this.cboITEMGROUP.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboITEMGROUP.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboITEMGROUP.DbConfig = null;
            this.cboITEMGROUP.DefaultValue = "";
            appearance104.BackColor = System.Drawing.SystemColors.Window;
            appearance104.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboITEMGROUP.DisplayLayout.Appearance = appearance104;
            this.cboITEMGROUP.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboITEMGROUP.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboITEMGROUP.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance105.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance105.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance105.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance105.BorderColor = System.Drawing.SystemColors.Window;
            this.cboITEMGROUP.DisplayLayout.GroupByBox.Appearance = appearance105;
            appearance106.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboITEMGROUP.DisplayLayout.GroupByBox.BandLabelAppearance = appearance106;
            this.cboITEMGROUP.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance107.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance107.BackColor2 = System.Drawing.SystemColors.Control;
            appearance107.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance107.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboITEMGROUP.DisplayLayout.GroupByBox.PromptAppearance = appearance107;
            this.cboITEMGROUP.DisplayLayout.MaxColScrollRegions = 1;
            this.cboITEMGROUP.DisplayLayout.MaxRowScrollRegions = 1;
            appearance108.BackColor = System.Drawing.SystemColors.Window;
            appearance108.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboITEMGROUP.DisplayLayout.Override.ActiveCellAppearance = appearance108;
            appearance109.BackColor = System.Drawing.SystemColors.Highlight;
            appearance109.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboITEMGROUP.DisplayLayout.Override.ActiveRowAppearance = appearance109;
            appearance110.FontData.BoldAsString = "True";
            this.cboITEMGROUP.DisplayLayout.Override.ActiveRowCellAppearance = appearance110;
            this.cboITEMGROUP.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboITEMGROUP.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboITEMGROUP.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance111.BackColor = System.Drawing.SystemColors.Window;
            this.cboITEMGROUP.DisplayLayout.Override.CardAreaAppearance = appearance111;
            appearance112.BorderColor = System.Drawing.Color.Silver;
            appearance112.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboITEMGROUP.DisplayLayout.Override.CellAppearance = appearance112;
            this.cboITEMGROUP.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboITEMGROUP.DisplayLayout.Override.CellPadding = 0;
            appearance113.BackColor = System.Drawing.SystemColors.Control;
            appearance113.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance113.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance113.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance113.BorderColor = System.Drawing.SystemColors.Window;
            this.cboITEMGROUP.DisplayLayout.Override.GroupByRowAppearance = appearance113;
            appearance114.TextHAlignAsString = "Left";
            this.cboITEMGROUP.DisplayLayout.Override.HeaderAppearance = appearance114;
            this.cboITEMGROUP.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboITEMGROUP.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance115.BackColor = System.Drawing.SystemColors.Window;
            appearance115.BorderColor = System.Drawing.Color.Silver;
            this.cboITEMGROUP.DisplayLayout.Override.RowAppearance = appearance115;
            this.cboITEMGROUP.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance116.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance116.FontData.BoldAsString = "True";
            this.cboITEMGROUP.DisplayLayout.Override.SelectedRowAppearance = appearance116;
            appearance117.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboITEMGROUP.DisplayLayout.Override.TemplateAddRowAppearance = appearance117;
            this.cboITEMGROUP.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboITEMGROUP.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboITEMGROUP.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboITEMGROUP.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboITEMGROUP.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboITEMGROUP.Location = new System.Drawing.Point(492, 128);
            this.cboITEMGROUP.MajorCode = "ITEMGROUP";
            this.cboITEMGROUP.Name = "cboITEMGROUP";
            this.cboITEMGROUP.ShowDefaultValue = false;
            this.cboITEMGROUP.Size = new System.Drawing.Size(154, 25);
            this.cboITEMGROUP.TabIndex = 27;
            // 
            // cboITEMSPEC
            // 
            this.cboITEMSPEC.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboITEMSPEC.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboITEMSPEC.DbConfig = null;
            this.cboITEMSPEC.DefaultValue = "";
            appearance118.BackColor = System.Drawing.SystemColors.Window;
            appearance118.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboITEMSPEC.DisplayLayout.Appearance = appearance118;
            this.cboITEMSPEC.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboITEMSPEC.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboITEMSPEC.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance119.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance119.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance119.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance119.BorderColor = System.Drawing.SystemColors.Window;
            this.cboITEMSPEC.DisplayLayout.GroupByBox.Appearance = appearance119;
            appearance120.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboITEMSPEC.DisplayLayout.GroupByBox.BandLabelAppearance = appearance120;
            this.cboITEMSPEC.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance121.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance121.BackColor2 = System.Drawing.SystemColors.Control;
            appearance121.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance121.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboITEMSPEC.DisplayLayout.GroupByBox.PromptAppearance = appearance121;
            this.cboITEMSPEC.DisplayLayout.MaxColScrollRegions = 1;
            this.cboITEMSPEC.DisplayLayout.MaxRowScrollRegions = 1;
            appearance122.BackColor = System.Drawing.SystemColors.Window;
            appearance122.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboITEMSPEC.DisplayLayout.Override.ActiveCellAppearance = appearance122;
            appearance123.BackColor = System.Drawing.SystemColors.Highlight;
            appearance123.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboITEMSPEC.DisplayLayout.Override.ActiveRowAppearance = appearance123;
            appearance124.FontData.BoldAsString = "True";
            this.cboITEMSPEC.DisplayLayout.Override.ActiveRowCellAppearance = appearance124;
            this.cboITEMSPEC.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboITEMSPEC.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboITEMSPEC.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance125.BackColor = System.Drawing.SystemColors.Window;
            this.cboITEMSPEC.DisplayLayout.Override.CardAreaAppearance = appearance125;
            appearance126.BorderColor = System.Drawing.Color.Silver;
            appearance126.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboITEMSPEC.DisplayLayout.Override.CellAppearance = appearance126;
            this.cboITEMSPEC.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboITEMSPEC.DisplayLayout.Override.CellPadding = 0;
            appearance127.BackColor = System.Drawing.SystemColors.Control;
            appearance127.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance127.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance127.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance127.BorderColor = System.Drawing.SystemColors.Window;
            this.cboITEMSPEC.DisplayLayout.Override.GroupByRowAppearance = appearance127;
            appearance128.TextHAlignAsString = "Left";
            this.cboITEMSPEC.DisplayLayout.Override.HeaderAppearance = appearance128;
            this.cboITEMSPEC.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboITEMSPEC.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance129.BackColor = System.Drawing.SystemColors.Window;
            appearance129.BorderColor = System.Drawing.Color.Silver;
            this.cboITEMSPEC.DisplayLayout.Override.RowAppearance = appearance129;
            this.cboITEMSPEC.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance130.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance130.FontData.BoldAsString = "True";
            this.cboITEMSPEC.DisplayLayout.Override.SelectedRowAppearance = appearance130;
            appearance131.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboITEMSPEC.DisplayLayout.Override.TemplateAddRowAppearance = appearance131;
            this.cboITEMSPEC.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboITEMSPEC.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboITEMSPEC.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboITEMSPEC.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboITEMSPEC.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboITEMSPEC.Location = new System.Drawing.Point(332, 128);
            this.cboITEMSPEC.MajorCode = "ITEMSPEC";
            this.cboITEMSPEC.Name = "cboITEMSPEC";
            this.cboITEMSPEC.ShowDefaultValue = false;
            this.cboITEMSPEC.Size = new System.Drawing.Size(154, 25);
            this.cboITEMSPEC.TabIndex = 26;
            // 
            // cboWHCode
            // 
            this.cboWHCode.AutoSize = false;
            this.cboWHCode.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboWHCode.ComboDataType = SAMMI.Control.ComboDataType.CodeOnly;
            this.cboWHCode.DataMember = "dTable1";
            this.cboWHCode.DbConfig = null;
            this.cboWHCode.DefaultValue = "";
            ultraGridColumn3.Header.VisiblePosition = 0;
            ultraGridColumn4.Header.VisiblePosition = 1;
            ultraGridBand3.Columns.AddRange(new object[] {
            ultraGridColumn3,
            ultraGridColumn4});
            this.cboWHCode.DisplayLayout.BandsSerializer.Add(ultraGridBand3);
            this.cboWHCode.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            this.cboWHCode.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance132.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance132.BackColorAlpha = Infragistics.Win.Alpha.UseAlphaLevel;
            appearance132.FontData.BoldAsString = "True";
            appearance132.ForeColor = System.Drawing.Color.White;
            this.cboWHCode.DisplayLayout.Override.ActiveRowAppearance = appearance132;
            appearance133.FontData.BoldAsString = "True";
            this.cboWHCode.DisplayLayout.Override.ActiveRowCellAppearance = appearance133;
            this.cboWHCode.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.None;
            this.cboWHCode.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.None;
            this.cboWHCode.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance134.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance134.FontData.BoldAsString = "True";
            this.cboWHCode.DisplayLayout.Override.SelectedRowAppearance = appearance134;
            this.cboWHCode.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboWHCode.DisplayMember = "WHName";
            this.cboWHCode.Font = new System.Drawing.Font("맑은 고딕", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboWHCode.Location = new System.Drawing.Point(640, 162);
            this.cboWHCode.Name = "cboWHCode";
            this.cboWHCode.PlantCode = null;
            this.cboWHCode.ShowDefaultValue = false;
            this.cboWHCode.Size = new System.Drawing.Size(254, 32);
            this.cboWHCode.TabIndex = 33;
            this.cboWHCode.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.cboWHCode.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.cboWHCode.ValueMember = "WHCode";
            // 
            // grid1
            // 
            this.grid1.ContextMenuCopyEnabled = true;
            this.grid1.ContextMenuDeleteEnabled = true;
            this.grid1.ContextMenuExcelEnabled = true;
            this.grid1.ContextMenuInsertEnabled = true;
            this.grid1.ContextMenuPasteEnabled = true;
            appearance148.BackColor = System.Drawing.SystemColors.Window;
            appearance148.BorderColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.Appearance = appearance148;
            appearance149.FontData.BoldAsString = "True";
            ultraGridBand1.Override.FixedCellAppearance = appearance149;
            this.grid1.DisplayLayout.BandsSerializer.Add(ultraGridBand1);
            this.grid1.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grid1.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.grid1.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.Empty;
            appearance150.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance150.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance150.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance150.BorderColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.GroupByBox.Appearance = appearance150;
            appearance38.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grid1.DisplayLayout.GroupByBox.BandLabelAppearance = appearance38;
            this.grid1.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.grid1.DisplayLayout.GroupByBox.Hidden = true;
            appearance39.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance39.BackColor2 = System.Drawing.SystemColors.Control;
            appearance39.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance39.ForeColor = System.Drawing.SystemColors.GrayText;
            this.grid1.DisplayLayout.GroupByBox.PromptAppearance = appearance39;
            appearance40.BackColor = System.Drawing.SystemColors.Window;
            appearance40.ForeColor = System.Drawing.SystemColors.ControlText;
            this.grid1.DisplayLayout.Override.ActiveCellAppearance = appearance40;
            appearance41.BackColor = System.Drawing.SystemColors.Highlight;
            appearance41.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.grid1.DisplayLayout.Override.ActiveRowAppearance = appearance41;
            this.grid1.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.True;
            this.grid1.DisplayLayout.Override.AllowMultiCellOperations = ((Infragistics.Win.UltraWinGrid.AllowMultiCellOperation)((((((((Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.CopyWithHeaders) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Cut) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Delete) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Paste) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Undo) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Redo) 
            | Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Reserved)));
            this.grid1.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.grid1.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance42.BackColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.Override.CardAreaAppearance = appearance42;
            appearance43.BorderColor = System.Drawing.Color.Silver;
            appearance43.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.grid1.DisplayLayout.Override.CellAppearance = appearance43;
            this.grid1.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.grid1.DisplayLayout.Override.CellPadding = 0;
            appearance44.BackColor = System.Drawing.SystemColors.Control;
            appearance44.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance44.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance44.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance44.BorderColor = System.Drawing.SystemColors.Window;
            this.grid1.DisplayLayout.Override.GroupByRowAppearance = appearance44;
            appearance45.TextHAlignAsString = "Left";
            this.grid1.DisplayLayout.Override.HeaderAppearance = appearance45;
            this.grid1.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.grid1.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance46.BackColor = System.Drawing.SystemColors.Window;
            appearance46.BorderColor = System.Drawing.Color.Silver;
            this.grid1.DisplayLayout.Override.RowAppearance = appearance46;
            this.grid1.DisplayLayout.Override.RowSelectorHeaderStyle = Infragistics.Win.UltraWinGrid.RowSelectorHeaderStyle.SeparateElement;
            this.grid1.DisplayLayout.Override.RowSelectorNumberStyle = Infragistics.Win.UltraWinGrid.RowSelectorNumberStyle.RowIndex;
            this.grid1.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.True;
            this.grid1.DisplayLayout.Override.RowSelectorStyle = Infragistics.Win.HeaderStyle.XPThemed;
            appearance47.BackColor = System.Drawing.SystemColors.ControlLight;
            this.grid1.DisplayLayout.Override.TemplateAddRowAppearance = appearance47;
            this.grid1.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.grid1.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.grid1.DisplayLayout.SelectionOverlayBorderThickness = 2;
            this.grid1.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.grid1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grid1.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.grid1.Location = new System.Drawing.Point(6, 6);
            this.grid1.Name = "grid1";
            this.grid1.Size = new System.Drawing.Size(1016, 663);
            this.grid1.TabIndex = 0;
            this.grid1.Text = "grid1";
            this.grid1.TextRenderingMode = Infragistics.Win.TextRenderingMode.GDIPlus;
            this.grid1.UpdateMode = Infragistics.Win.UltraWinGrid.UpdateMode.OnCellChange;
            this.grid1.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.grid1.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.grid1.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.grid1_InitializeLayout);
            // 
            // lblPlantCode
            // 
            appearance34.TextHAlignAsString = "Right";
            appearance34.TextVAlignAsString = "Middle";
            this.lblPlantCode.Appearance = appearance34;
            this.lblPlantCode.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.lblPlantCode.DbField = null;
            this.lblPlantCode.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblPlantCode.Location = new System.Drawing.Point(803, 7);
            this.lblPlantCode.Name = "lblPlantCode";
            this.lblPlantCode.Size = new System.Drawing.Size(58, 25);
            this.lblPlantCode.TabIndex = 19;
            this.lblPlantCode.Text = "사업장";
            this.lblPlantCode.Visible = false;
            // 
            // txtPlantCode
            // 
            this.txtPlantCode.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtPlantCode.Location = new System.Drawing.Point(869, 7);
            this.txtPlantCode.Name = "txtPlantCode";
            this.txtPlantCode.ReadOnly = true;
            this.txtPlantCode.Size = new System.Drawing.Size(152, 25);
            this.txtPlantCode.TabIndex = 23;
            this.txtPlantCode.Visible = false;
            // 
            // cboUseFlag_H
            // 
            appearance135.FontData.Name = "맑은 고딕";
            appearance135.FontData.SizeInPoints = 9F;
            this.cboUseFlag_H.Appearance = appearance135;
            this.cboUseFlag_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboUseFlag_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboUseFlag_H.DbConfig = null;
            this.cboUseFlag_H.DefaultValue = "ALL";
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboUseFlag_H.DisplayLayout.Appearance = appearance17;
            this.cboUseFlag_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboUseFlag_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboUseFlag_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance18.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance18.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance18.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance18.BorderColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag_H.DisplayLayout.GroupByBox.Appearance = appearance18;
            appearance19.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboUseFlag_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance19;
            this.cboUseFlag_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance20.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance20.BackColor2 = System.Drawing.SystemColors.Control;
            appearance20.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance20.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboUseFlag_H.DisplayLayout.GroupByBox.PromptAppearance = appearance20;
            this.cboUseFlag_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboUseFlag_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance21.BackColor = System.Drawing.SystemColors.Window;
            appearance21.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboUseFlag_H.DisplayLayout.Override.ActiveCellAppearance = appearance21;
            appearance136.BackColor = System.Drawing.SystemColors.Highlight;
            appearance136.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboUseFlag_H.DisplayLayout.Override.ActiveRowAppearance = appearance136;
            appearance23.FontData.BoldAsString = "True";
            this.cboUseFlag_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance23;
            this.cboUseFlag_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboUseFlag_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboUseFlag_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance24.BackColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag_H.DisplayLayout.Override.CardAreaAppearance = appearance24;
            appearance25.BorderColor = System.Drawing.Color.Silver;
            appearance25.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboUseFlag_H.DisplayLayout.Override.CellAppearance = appearance25;
            this.cboUseFlag_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboUseFlag_H.DisplayLayout.Override.CellPadding = 0;
            appearance26.BackColor = System.Drawing.SystemColors.Control;
            appearance26.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance26.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance26.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance26.BorderColor = System.Drawing.SystemColors.Window;
            this.cboUseFlag_H.DisplayLayout.Override.GroupByRowAppearance = appearance26;
            appearance27.TextHAlignAsString = "Left";
            this.cboUseFlag_H.DisplayLayout.Override.HeaderAppearance = appearance27;
            this.cboUseFlag_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboUseFlag_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance28.BackColor = System.Drawing.SystemColors.Window;
            appearance28.BorderColor = System.Drawing.Color.Silver;
            this.cboUseFlag_H.DisplayLayout.Override.RowAppearance = appearance28;
            this.cboUseFlag_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance29.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance29.FontData.BoldAsString = "True";
            this.cboUseFlag_H.DisplayLayout.Override.SelectedRowAppearance = appearance29;
            appearance30.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboUseFlag_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance30;
            this.cboUseFlag_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboUseFlag_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboUseFlag_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboUseFlag_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboUseFlag_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboUseFlag_H.Location = new System.Drawing.Point(273, 7);
            this.cboUseFlag_H.MajorCode = "USEFLAG";
            this.cboUseFlag_H.Name = "cboUseFlag_H";
            this.cboUseFlag_H.ShowDefaultValue = false;
            this.cboUseFlag_H.Size = new System.Drawing.Size(121, 24);
            this.cboUseFlag_H.TabIndex = 3;
            this.cboUseFlag_H.Text = "ALL";
            // 
            // cboItemType_H
            // 
            appearance1.FontData.Name = "맑은 고딕";
            appearance1.FontData.SizeInPoints = 9F;
            this.cboItemType_H.Appearance = appearance1;
            this.cboItemType_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboItemType_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboItemType_H.DbConfig = null;
            this.cboItemType_H.DefaultValue = "ALL";
            appearance137.BackColor = System.Drawing.SystemColors.Window;
            appearance137.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboItemType_H.DisplayLayout.Appearance = appearance137;
            this.cboItemType_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboItemType_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboItemType_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance3.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance3.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance3.BorderColor = System.Drawing.SystemColors.Window;
            this.cboItemType_H.DisplayLayout.GroupByBox.Appearance = appearance3;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboItemType_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance4;
            this.cboItemType_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance5.BackColor2 = System.Drawing.SystemColors.Control;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboItemType_H.DisplayLayout.GroupByBox.PromptAppearance = appearance5;
            this.cboItemType_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboItemType_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance138.BackColor = System.Drawing.SystemColors.Window;
            appearance138.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboItemType_H.DisplayLayout.Override.ActiveCellAppearance = appearance138;
            appearance139.BackColor = System.Drawing.SystemColors.Highlight;
            appearance139.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboItemType_H.DisplayLayout.Override.ActiveRowAppearance = appearance139;
            appearance140.FontData.BoldAsString = "True";
            this.cboItemType_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance140;
            this.cboItemType_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboItemType_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboItemType_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance141.BackColor = System.Drawing.SystemColors.Window;
            this.cboItemType_H.DisplayLayout.Override.CardAreaAppearance = appearance141;
            appearance142.BorderColor = System.Drawing.Color.Silver;
            appearance142.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboItemType_H.DisplayLayout.Override.CellAppearance = appearance142;
            this.cboItemType_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboItemType_H.DisplayLayout.Override.CellPadding = 0;
            appearance143.BackColor = System.Drawing.SystemColors.Control;
            appearance143.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance143.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance143.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance143.BorderColor = System.Drawing.SystemColors.Window;
            this.cboItemType_H.DisplayLayout.Override.GroupByRowAppearance = appearance143;
            appearance144.TextHAlignAsString = "Left";
            this.cboItemType_H.DisplayLayout.Override.HeaderAppearance = appearance144;
            this.cboItemType_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboItemType_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance145.BackColor = System.Drawing.SystemColors.Window;
            appearance145.BorderColor = System.Drawing.Color.Silver;
            this.cboItemType_H.DisplayLayout.Override.RowAppearance = appearance145;
            this.cboItemType_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance146.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance146.FontData.BoldAsString = "True";
            this.cboItemType_H.DisplayLayout.Override.SelectedRowAppearance = appearance146;
            appearance147.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboItemType_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance147;
            this.cboItemType_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboItemType_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboItemType_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboItemType_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboItemType_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboItemType_H.Location = new System.Drawing.Point(478, 7);
            this.cboItemType_H.MajorCode = "ITEMTYPE";
            this.cboItemType_H.Name = "cboItemType_H";
            this.cboItemType_H.ShowDefaultValue = false;
            this.cboItemType_H.Size = new System.Drawing.Size(121, 24);
            this.cboItemType_H.TabIndex = 4;
            this.cboItemType_H.Text = "ALL";
            // 
            // txtItemName
            // 
            this.txtItemName.BackColor = System.Drawing.SystemColors.InactiveBorder;
            this.txtItemName.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.txtItemName.Location = new System.Drawing.Point(195, 36);
            this.txtItemName.Name = "txtItemName";
            this.txtItemName.Size = new System.Drawing.Size(199, 25);
            this.txtItemName.TabIndex = 2;
            // 
            // cboPlantCode_H
            // 
            appearance2.FontData.Name = "맑은 고딕";
            appearance2.FontData.SizeInPoints = 9F;
            this.cboPlantCode_H.Appearance = appearance2;
            this.cboPlantCode_H.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboPlantCode_H.ComboDataType = SAMMI.Control.ComboDataType.All;
            this.cboPlantCode_H.DbConfig = null;
            this.cboPlantCode_H.DefaultValue = "ALL";
            appearance35.BackColor = System.Drawing.SystemColors.Window;
            appearance35.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.cboPlantCode_H.DisplayLayout.Appearance = appearance35;
            this.cboPlantCode_H.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.cboPlantCode_H.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.cboPlantCode_H.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance36.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance36.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance36.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance36.BorderColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.Appearance = appearance36;
            appearance37.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.BandLabelAppearance = appearance37;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance6.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance6.BackColor2 = System.Drawing.SystemColors.Control;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.cboPlantCode_H.DisplayLayout.GroupByBox.PromptAppearance = appearance6;
            this.cboPlantCode_H.DisplayLayout.MaxColScrollRegions = 1;
            this.cboPlantCode_H.DisplayLayout.MaxRowScrollRegions = 1;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            appearance7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cboPlantCode_H.DisplayLayout.Override.ActiveCellAppearance = appearance7;
            appearance8.BackColor = System.Drawing.SystemColors.Highlight;
            appearance8.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.cboPlantCode_H.DisplayLayout.Override.ActiveRowAppearance = appearance8;
            appearance9.FontData.BoldAsString = "True";
            this.cboPlantCode_H.DisplayLayout.Override.ActiveRowCellAppearance = appearance9;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.cboPlantCode_H.DisplayLayout.Override.BorderStyleSpecialRowSeparator = Infragistics.Win.UIElementBorderStyle.None;
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.Override.CardAreaAppearance = appearance10;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            appearance11.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.cboPlantCode_H.DisplayLayout.Override.CellAppearance = appearance11;
            this.cboPlantCode_H.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.cboPlantCode_H.DisplayLayout.Override.CellPadding = 0;
            appearance12.BackColor = System.Drawing.SystemColors.Control;
            appearance12.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance12.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance12.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance12.BorderColor = System.Drawing.SystemColors.Window;
            this.cboPlantCode_H.DisplayLayout.Override.GroupByRowAppearance = appearance12;
            appearance13.TextHAlignAsString = "Left";
            this.cboPlantCode_H.DisplayLayout.Override.HeaderAppearance = appearance13;
            this.cboPlantCode_H.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.cboPlantCode_H.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            this.cboPlantCode_H.DisplayLayout.Override.RowAppearance = appearance14;
            this.cboPlantCode_H.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance15.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(99)))), ((int)(((byte)(133)))), ((int)(((byte)(188)))));
            appearance15.FontData.BoldAsString = "True";
            this.cboPlantCode_H.DisplayLayout.Override.SelectedRowAppearance = appearance15;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.cboPlantCode_H.DisplayLayout.Override.TemplateAddRowAppearance = appearance16;
            this.cboPlantCode_H.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.cboPlantCode_H.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.cboPlantCode_H.DisplayLayout.ViewStyle = Infragistics.Win.UltraWinGrid.ViewStyle.SingleBand;
            this.cboPlantCode_H.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.cboPlantCode_H.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.cboPlantCode_H.Location = new System.Drawing.Point(70, 7);
            this.cboPlantCode_H.MajorCode = "PLANTCODE";
            this.cboPlantCode_H.Name = "cboPlantCode_H";
            this.cboPlantCode_H.ShowDefaultValue = false;
            this.cboPlantCode_H.Size = new System.Drawing.Size(119, 24);
            this.cboPlantCode_H.TabIndex = 553;
            this.cboPlantCode_H.Text = "ALL";
            // 
            // sLabel5
            // 
            appearance22.TextHAlignAsString = "Right";
            appearance22.TextVAlignAsString = "Middle";
            this.sLabel5.Appearance = appearance22;
            this.sLabel5.BorderStyleInner = Infragistics.Win.UIElementBorderStyle.None;
            this.sLabel5.DbField = "cboUseFlag";
            this.sLabel5.Font = new System.Drawing.Font("맑은 고딕", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.sLabel5.Location = new System.Drawing.Point(12, 6);
            this.sLabel5.Name = "sLabel5";
            this.sLabel5.Size = new System.Drawing.Size(52, 26);
            this.sLabel5.TabIndex = 552;
            this.sLabel5.Text = "사업장";
            // 
            // BM5100
            // 
            this.ClientSize = new System.Drawing.Size(1028, 746);
            this.Name = "BM5100";
            this.Load += new System.EventHandler(this.BM5100_Load);
            ((System.ComponentModel.ISupportInitialize)(this.gbxHeader)).EndInit();
            this.gbxHeader.ResumeLayout(false);
            this.gbxHeader.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gbxBody)).EndInit();
            this.gbxBody.ResumeLayout(false);
            this.gbxBody.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cboUseFlag)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboCarType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cbotUnitCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboYesNo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboITEMGROUP)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboITEMSPEC)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboWHCode)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grid1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboUseFlag_H)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboItemType_H)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cboPlantCode_H)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Control.SLabel lblItemCode;
        private Control.SLabel lblItemType;
        private Control.SLabel lblUseFlag;
        private Control.SCodeNMComboBox cboUseFlag;
        private Control.SCodeNMComboBox cboCarType;
        private Control.ScboGetUnitCode cbotUnitCode;
        private Control.SCodeNMComboBox cboYesNo;
        private Control.SCodeNMComboBox cboITEMGROUP;
        private Control.SCodeNMComboBox cboITEMSPEC;
        private System.Windows.Forms.TextBox txtItemCode;
        private Control.ScboGetWHCode cboWHCode;
        private Control.Grid grid1;
        private System.Windows.Forms.TextBox txtPlantCode;
        private Control.SLabel lblPlantCode;
        private Control.SCodeNMComboBox cboUseFlag_H;
        private Control.SCodeNMComboBox cboItemType_H;
        private System.Windows.Forms.TextBox txtItemName;
        private Control.SCodeNMComboBox cboPlantCode_H;
        private Control.SLabel sLabel5;

    }
}
